# -*- coding: utf-8 -*-
"""
Financial Dashboard - Multi-asset Comparison
Enhanced version with metrics, drawdowns, news, multilingual support, and Credit Risk Analysis
"""

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime, timedelta
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import feedparser
import requests
from scipy.stats import norm

# =============================================================================
# TRANSLATIONS
# =============================================================================
TRANSLATIONS = {
    "English": {
        # General
        "page_title": "Financial Dashboard",
        "main_title": "📈 Financial Dashboard",
        "comparison": "Comparison",
        "vs": "vs",
        "years": "years",
        "over": "over",
        
        # Sidebar
        "settings": "⚙️ Settings",
        "language": "🌐 Language",
        "asset_selection": "Asset Selection",
        "first_asset": "First asset",
        "second_asset": "Second asset",
        "period": "Period",
        "num_years": "Number of years",
        "display_options": "Display Options",
        "show_normalized": "Show normalized prices",
        "show_drawdown": "Show drawdowns",
        "show_volume": "Show volumes",
        "refresh_data": "🔄 Refresh data",
        "last_update": "Last update",
        "created_with": "Dashboard created with Streamlit",
        
        # Asset categories
        "cryptocurrencies": "Cryptocurrencies",
        "indices": "Indices",
        "tech_stocks": "Tech Stocks",
        "commodities": "Commodities",
        
        # Metrics
        "key_metrics": "📊 Key Metrics",
        "return": "Return",
        "volatility": "Volatility",
        "current_price": "Current Price",
        "sharpe": "Sharpe",
        
        # Charts
        "performance_comparison": "📈 Performance Comparison",
        "normalized_prices": "Normalized prices",
        "prices": "Prices",
        "normalized_price_zscore": "Normalized Price (z-score)",
        "price_usd": "Price ($)",
        "date": "Date",
        "asset": "Asset",
        
        # Drawdowns
        "drawdowns_title": "📉 Drawdowns (losses from peak)",
        "drawdowns_from_ath": "Drawdowns from all-time highs",
        "max_drawdown": "Max Drawdown",
        
        # Volume
        "trading_volumes": "📊 Trading Volumes",
        "volume": "Volume",
        
        # Correlation
        "correlation_analysis": "🔗 Correlation Analysis",
        "overall_correlation": "Overall Correlation",
        "rolling_correlation": "Rolling Correlation",
        "days": "days",
        "interpretation": "Interpretation",
        "strong_positive": "Strong positive correlation",
        "moderate": "Moderate correlation",
        "weak": "Weak correlation",
        "negative": "Negative correlation",
        
        # News
        "recent_news": "📰 Recent News",
        "no_news": "No news available",
        
        # Data
        "raw_data": "📋 Raw Data",
        "view_data": "View data",
        "merged_data": "View merged data",
        
        # Export
        "export_data": "💾 Export Data",
        "download": "📥 Download",
        
        # Errors
        "loading_data": "Loading data...",
        "error_loading": "Unable to load data. Please try again later.",
        "error_fetching": "Error fetching",
        
        # Economic Analysis
        "economic_analysis": "🌍 Economic Analysis by Continent",
        "select_continent": "Select a continent",
        "generate_analysis": "Generate Analysis",
        "analysis_disclaimer": "This analysis is generated by AI and should not be considered as financial advice.",
        "loading_analysis": "Generating economic analysis...",
        "api_key_required": "API Key Required",
        "api_key_help": "Get your free API key at",
        "enter_api_key": "Enter your Groq API key",
        "analysis_error": "Error generating analysis. Please check your API key and try again.",
        "continents": {
            "north_america": "North America",
            "south_america": "South America", 
            "europe": "Europe",
            "asia": "Asia",
            "africa": "Africa",
            "oceania": "Oceania"
        },
        "economic_indicators": "Key Economic Indicators",
        "ai_analysis": "AI Economic Analysis",
        "last_analysis": "Analysis generated on",
        
        # Credit Risk Analysis
        "credit_risk": "🏦 Credit Risk Analysis",
        "credit_risk_title": "Credit Risk Analysis",
        "enter_ticker": "Enter ticker symbol",
        "analyze_button": "Analyze Credit Risk",
        "merton_model": "Merton Structural Model",
        "ml_model": "ML Model (Historical)",
        "distance_to_default": "Distance to Default",
        "probability_of_default": "Probability of Default",
        "risk_category": "Risk Category",
        "very_low_risk": "Very Low Risk",
        "low_risk": "Low Risk",
        "moderate_risk": "Moderate Risk",
        "high_risk": "High Risk",
        "very_high_risk": "Very High Risk",
        "model_inputs": "Model Inputs",
        "market_cap": "Market Cap",
        "total_debt": "Total Debt",
        "asset_value": "Asset Value (V)",
        "equity_volatility": "Equity Volatility",
        "risk_free_rate": "Risk-Free Rate",
        "time_horizon": "Time Horizon",
        "merton_explanation": "The Merton model treats equity as a call option on firm assets. Default occurs if asset value falls below debt at maturity.",
        "ml_explanation": "ML model trained on historical bankruptcy data (1999-2018). Note: Live predictions require feature mapping from financial statements.",
        "data_unavailable": "Required financial data not available for this ticker.",
        "analyzing": "Analyzing credit risk...",
        "credit_risk_comparison": "Credit Risk Comparison",
        "benchmark_companies": "Benchmark Companies",
    },
    
    "Français": {
        # General
        "page_title": "Dashboard Financier",
        "main_title": "📈 Dashboard Financier",
        "comparison": "Comparaison",
        "vs": "vs",
        "years": "ans",
        "over": "sur",
        
        # Sidebar
        "settings": "⚙️ Paramètres",
        "language": "🌐 Langue",
        "asset_selection": "Sélection des actifs",
        "first_asset": "Premier actif",
        "second_asset": "Deuxième actif",
        "period": "Période",
        "num_years": "Nombre d'années",
        "display_options": "Options d'affichage",
        "show_normalized": "Afficher les prix normalisés",
        "show_drawdown": "Afficher les drawdowns",
        "show_volume": "Afficher les volumes",
        "refresh_data": "🔄 Rafraîchir les données",
        "last_update": "Dernière mise à jour",
        "created_with": "Dashboard créé avec Streamlit",
        
        # Asset categories
        "cryptocurrencies": "Cryptomonnaies",
        "indices": "Indices",
        "tech_stocks": "Actions Tech",
        "commodities": "Matières premières",
        
        # Metrics
        "key_metrics": "📊 Métriques clés",
        "return": "Rendement",
        "volatility": "Volatilité",
        "current_price": "Prix actuel",
        "sharpe": "Sharpe",
        
        # Charts
        "performance_comparison": "📈 Comparaison des performances",
        "normalized_prices": "Prix normalisés",
        "prices": "Prix",
        "normalized_price_zscore": "Prix normalisé (z-score)",
        "price_usd": "Prix ($)",
        "date": "Date",
        "asset": "Actif",
        
        # Drawdowns
        "drawdowns_title": "📉 Drawdowns (pertes depuis le plus haut)",
        "drawdowns_from_ath": "Drawdowns depuis les plus hauts historiques",
        "max_drawdown": "Drawdown max",
        
        # Volume
        "trading_volumes": "📊 Volumes d'échange",
        "volume": "Volume",
        
        # Correlation
        "correlation_analysis": "🔗 Analyse de corrélation",
        "overall_correlation": "Corrélation globale",
        "rolling_correlation": "Corrélation glissante",
        "days": "jours",
        "interpretation": "Interprétation",
        "strong_positive": "Forte corrélation positive",
        "moderate": "Corrélation modérée",
        "weak": "Faible corrélation",
        "negative": "Corrélation négative",
        
        # News
        "recent_news": "📰 Actualités récentes",
        "no_news": "Aucune actualité disponible",
        
        # Data
        "raw_data": "📋 Données brutes",
        "view_data": "Voir les données",
        "merged_data": "Voir les données fusionnées",
        
        # Export
        "export_data": "💾 Exporter les données",
        "download": "📥 Télécharger",
        
        # Errors
        "loading_data": "Chargement des données...",
        "error_loading": "Impossible de charger les données. Veuillez réessayer plus tard.",
        "error_fetching": "Erreur lors du chargement de",
        
        # Economic Analysis
        "economic_analysis": "🌍 Analyse Économique par Continent",
        "select_continent": "Sélectionner un continent",
        "generate_analysis": "Générer l'analyse",
        "analysis_disclaimer": "Cette analyse est générée par IA et ne constitue pas un conseil financier.",
        "loading_analysis": "Génération de l'analyse économique...",
        "api_key_required": "Clé API requise",
        "api_key_help": "Obtenez votre clé API gratuite sur",
        "enter_api_key": "Entrez votre clé API Groq",
        "analysis_error": "Erreur lors de la génération. Vérifiez votre clé API et réessayez.",
        "continents": {
            "north_america": "Amérique du Nord",
            "south_america": "Amérique du Sud",
            "europe": "Europe",
            "asia": "Asie",
            "africa": "Afrique",
            "oceania": "Océanie"
        },
        "economic_indicators": "Indicateurs Économiques Clés",
        "ai_analysis": "Analyse Économique IA",
        "last_analysis": "Analyse générée le",
        
        # Credit Risk Analysis
        "credit_risk": "🏦 Analyse du Risque de Crédit",
        "credit_risk_title": "Analyse du Risque de Crédit",
        "enter_ticker": "Entrez le symbole boursier",
        "analyze_button": "Analyser le Risque de Crédit",
        "merton_model": "Modèle Structurel de Merton",
        "ml_model": "Modèle ML (Historique)",
        "distance_to_default": "Distance au Défaut",
        "probability_of_default": "Probabilité de Défaut",
        "risk_category": "Catégorie de Risque",
        "very_low_risk": "Risque Très Faible",
        "low_risk": "Risque Faible",
        "moderate_risk": "Risque Modéré",
        "high_risk": "Risque Élevé",
        "very_high_risk": "Risque Très Élevé",
        "model_inputs": "Entrées du Modèle",
        "market_cap": "Capitalisation Boursière",
        "total_debt": "Dette Totale",
        "asset_value": "Valeur des Actifs (V)",
        "equity_volatility": "Volatilité des Actions",
        "risk_free_rate": "Taux Sans Risque",
        "time_horizon": "Horizon Temporel",
        "merton_explanation": "Le modèle de Merton traite les capitaux propres comme une option d'achat sur les actifs de l'entreprise.",
        "ml_explanation": "Modèle ML entraîné sur des données historiques de faillite (1999-2018).",
        "data_unavailable": "Données financières requises non disponibles pour ce ticker.",
        "analyzing": "Analyse du risque de crédit en cours...",
        "credit_risk_comparison": "Comparaison du Risque de Crédit",
        "benchmark_companies": "Entreprises de Référence",
    },
    
    "Español": {
        "page_title": "Panel Financiero",
        "main_title": "📈 Panel Financiero",
        "comparison": "Comparación",
        "vs": "vs",
        "years": "años",
        "over": "durante",
        "settings": "⚙️ Configuración",
        "language": "🌐 Idioma",
        "asset_selection": "Selección de activos",
        "first_asset": "Primer activo",
        "second_asset": "Segundo activo",
        "period": "Período",
        "num_years": "Número de años",
        "display_options": "Opciones de visualización",
        "show_normalized": "Mostrar precios normalizados",
        "show_drawdown": "Mostrar drawdowns",
        "show_volume": "Mostrar volúmenes",
        "refresh_data": "🔄 Actualizar datos",
        "last_update": "Última actualización",
        "created_with": "Panel creado con Streamlit",
        "cryptocurrencies": "Criptomonedas",
        "indices": "Índices",
        "tech_stocks": "Acciones tecnológicas",
        "commodities": "Materias primas",
        "key_metrics": "📊 Métricas clave",
        "return": "Rendimiento",
        "volatility": "Volatilidad",
        "current_price": "Precio actual",
        "sharpe": "Sharpe",
        "performance_comparison": "📈 Comparación de rendimiento",
        "normalized_prices": "Precios normalizados",
        "prices": "Precios",
        "normalized_price_zscore": "Precio normalizado (z-score)",
        "price_usd": "Precio ($)",
        "date": "Fecha",
        "asset": "Activo",
        "drawdowns_title": "📉 Drawdowns (pérdidas desde máximos)",
        "drawdowns_from_ath": "Drawdowns desde máximos históricos",
        "max_drawdown": "Drawdown máximo",
        "trading_volumes": "📊 Volúmenes de negociación",
        "volume": "Volumen",
        "correlation_analysis": "🔗 Análisis de correlación",
        "overall_correlation": "Correlación global",
        "rolling_correlation": "Correlación móvil",
        "days": "días",
        "interpretation": "Interpretación",
        "strong_positive": "Fuerte correlación positiva",
        "moderate": "Correlación moderada",
        "weak": "Correlación débil",
        "negative": "Correlación negativa",
        "recent_news": "📰 Noticias recientes",
        "no_news": "No hay noticias disponibles",
        "raw_data": "📋 Datos brutos",
        "view_data": "Ver datos",
        "merged_data": "Ver datos combinados",
        "export_data": "💾 Exportar datos",
        "download": "📥 Descargar",
        "loading_data": "Cargando datos...",
        "error_loading": "No se pueden cargar los datos. Inténtelo de nuevo más tarde.",
        "error_fetching": "Error al cargar",
        "economic_analysis": "🌍 Análisis Económico por Continente",
        "select_continent": "Seleccionar un continente",
        "generate_analysis": "Generar Análisis",
        "analysis_disclaimer": "Este análisis es generado por IA y no debe considerarse como consejo financiero.",
        "loading_analysis": "Generando análisis económico...",
        "api_key_required": "Clave API requerida",
        "api_key_help": "Obtén tu clave API gratuita en",
        "enter_api_key": "Ingresa tu clave API de Groq",
        "analysis_error": "Error al generar el análisis. Verifica tu clave API e intenta de nuevo.",
        "continents": {
            "north_america": "América del Norte",
            "south_america": "América del Sur",
            "europe": "Europa",
            "asia": "Asia",
            "africa": "África",
            "oceania": "Oceanía"
        },
        "economic_indicators": "Indicadores Económicos Clave",
        "ai_analysis": "Análisis Económico IA",
        "last_analysis": "Análisis generado el",
        "credit_risk": "🏦 Análisis de Riesgo de Crédito",
        "credit_risk_title": "Análisis de Riesgo de Crédito",
        "enter_ticker": "Ingrese el símbolo bursátil",
        "analyze_button": "Analizar Riesgo de Crédito",
        "merton_model": "Modelo Estructural de Merton",
        "ml_model": "Modelo ML (Histórico)",
        "distance_to_default": "Distancia al Incumplimiento",
        "probability_of_default": "Probabilidad de Incumplimiento",
        "risk_category": "Categoría de Riesgo",
        "very_low_risk": "Riesgo Muy Bajo",
        "low_risk": "Riesgo Bajo",
        "moderate_risk": "Riesgo Moderado",
        "high_risk": "Riesgo Alto",
        "very_high_risk": "Riesgo Muy Alto",
        "model_inputs": "Entradas del Modelo",
        "market_cap": "Capitalización de Mercado",
        "total_debt": "Deuda Total",
        "asset_value": "Valor de Activos (V)",
        "equity_volatility": "Volatilidad de Acciones",
        "risk_free_rate": "Tasa Libre de Riesgo",
        "time_horizon": "Horizonte Temporal",
        "merton_explanation": "El modelo de Merton trata el capital como una opción de compra sobre los activos de la empresa.",
        "ml_explanation": "Modelo ML entrenado con datos históricos de quiebra (1999-2018).",
        "data_unavailable": "Datos financieros requeridos no disponibles para este ticker.",
        "analyzing": "Analizando riesgo de crédito...",
        "credit_risk_comparison": "Comparación de Riesgo de Crédito",
        "benchmark_companies": "Empresas de Referencia",
    },
    
    "中文": {
        "page_title": "金融仪表板",
        "main_title": "📈 金融仪表板",
        "comparison": "比较",
        "vs": "与",
        "years": "年",
        "over": "期间",
        "settings": "⚙️ 设置",
        "language": "🌐 语言",
        "asset_selection": "资产选择",
        "first_asset": "第一资产",
        "second_asset": "第二资产",
        "period": "时间段",
        "num_years": "年数",
        "display_options": "显示选项",
        "show_normalized": "显示标准化价格",
        "show_drawdown": "显示回撤",
        "show_volume": "显示成交量",
        "refresh_data": "🔄 刷新数据",
        "last_update": "最后更新",
        "created_with": "使用Streamlit创建的仪表板",
        "cryptocurrencies": "加密货币",
        "indices": "指数",
        "tech_stocks": "科技股",
        "commodities": "大宗商品",
        "key_metrics": "📊 关键指标",
        "return": "回报率",
        "volatility": "波动率",
        "current_price": "当前价格",
        "sharpe": "夏普比率",
        "performance_comparison": "📈 绩效比较",
        "normalized_prices": "标准化价格",
        "prices": "价格",
        "normalized_price_zscore": "标准化价格 (z-score)",
        "price_usd": "价格 ($)",
        "date": "日期",
        "asset": "资产",
        "drawdowns_title": "📉 回撤（从峰值的损失）",
        "drawdowns_from_ath": "从历史高点的回撤",
        "max_drawdown": "最大回撤",
        "trading_volumes": "📊 交易量",
        "volume": "成交量",
        "correlation_analysis": "🔗 相关性分析",
        "overall_correlation": "总体相关性",
        "rolling_correlation": "滚动相关性",
        "days": "天",
        "interpretation": "解释",
        "strong_positive": "强正相关",
        "moderate": "中等相关",
        "weak": "弱相关",
        "negative": "负相关",
        "recent_news": "📰 最新消息",
        "no_news": "暂无新闻",
        "raw_data": "📋 原始数据",
        "view_data": "查看数据",
        "merged_data": "查看合并数据",
        "export_data": "💾 导出数据",
        "download": "📥 下载",
        "loading_data": "加载数据中...",
        "error_loading": "无法加载数据，请稍后再试。",
        "error_fetching": "获取数据时出错",
        "economic_analysis": "🌍 各大洲经济分析",
        "select_continent": "选择一个大洲",
        "generate_analysis": "生成分析",
        "analysis_disclaimer": "此分析由AI生成，不应被视为财务建议。",
        "loading_analysis": "正在生成经济分析...",
        "api_key_required": "需要API密钥",
        "api_key_help": "在此获取免费API密钥",
        "enter_api_key": "输入您的Groq API密钥",
        "analysis_error": "生成分析时出错。请检查您的API密钥并重试。",
        "continents": {
            "north_america": "北美洲",
            "south_america": "南美洲",
            "europe": "欧洲",
            "asia": "亚洲",
            "africa": "非洲",
            "oceania": "大洋洲"
        },
        "economic_indicators": "关键经济指标",
        "ai_analysis": "AI经济分析",
        "last_analysis": "分析生成于",
        "credit_risk": "🏦 信用风险分析",
        "credit_risk_title": "信用风险分析",
        "enter_ticker": "输入股票代码",
        "analyze_button": "分析信用风险",
        "merton_model": "Merton结构模型",
        "ml_model": "机器学习模型（历史）",
        "distance_to_default": "违约距离",
        "probability_of_default": "违约概率",
        "risk_category": "风险类别",
        "very_low_risk": "极低风险",
        "low_risk": "低风险",
        "moderate_risk": "中等风险",
        "high_risk": "高风险",
        "very_high_risk": "极高风险",
        "model_inputs": "模型输入",
        "market_cap": "市值",
        "total_debt": "总债务",
        "asset_value": "资产价值 (V)",
        "equity_volatility": "股权波动率",
        "risk_free_rate": "无风险利率",
        "time_horizon": "时间范围",
        "merton_explanation": "Merton模型将股权视为公司资产的看涨期权。",
        "ml_explanation": "基于历史破产数据（1999-2018）训练的ML模型。",
        "data_unavailable": "此股票代码的必要财务数据不可用。",
        "analyzing": "正在分析信用风险...",
        "credit_risk_comparison": "信用风险比较",
        "benchmark_companies": "基准公司",
    },
    
    "Русский": {
        "page_title": "Финансовая панель",
        "main_title": "📈 Финансовая панель",
        "comparison": "Сравнение",
        "vs": "и",
        "years": "лет",
        "over": "за",
        "settings": "⚙️ Настройки",
        "language": "🌐 Язык",
        "asset_selection": "Выбор активов",
        "first_asset": "Первый актив",
        "second_asset": "Второй актив",
        "period": "Период",
        "num_years": "Количество лет",
        "display_options": "Параметры отображения",
        "show_normalized": "Показать нормализованные цены",
        "show_drawdown": "Показать просадки",
        "show_volume": "Показать объёмы",
        "refresh_data": "🔄 Обновить данные",
        "last_update": "Последнее обновление",
        "created_with": "Панель создана с помощью Streamlit",
        "cryptocurrencies": "Криптовалюты",
        "indices": "Индексы",
        "tech_stocks": "Технологические акции",
        "commodities": "Сырьевые товары",
        "key_metrics": "📊 Ключевые показатели",
        "return": "Доходность",
        "volatility": "Волатильность",
        "current_price": "Текущая цена",
        "sharpe": "Шарп",
        "performance_comparison": "📈 Сравнение эффективности",
        "normalized_prices": "Нормализованные цены",
        "prices": "Цены",
        "normalized_price_zscore": "Нормализованная цена (z-score)",
        "price_usd": "Цена ($)",
        "date": "Дата",
        "asset": "Актив",
        "drawdowns_title": "📉 Просадки (потери от максимума)",
        "drawdowns_from_ath": "Просадки от исторических максимумов",
        "max_drawdown": "Макс. просадка",
        "trading_volumes": "📊 Объёмы торгов",
        "volume": "Объём",
        "correlation_analysis": "🔗 Анализ корреляции",
        "overall_correlation": "Общая корреляция",
        "rolling_correlation": "Скользящая корреляция",
        "days": "дней",
        "interpretation": "Интерпретация",
        "strong_positive": "Сильная положительная корреляция",
        "moderate": "Умеренная корреляция",
        "weak": "Слабая корреляция",
        "negative": "Отрицательная корреляция",
        "recent_news": "📰 Последние новости",
        "no_news": "Новостей нет",
        "raw_data": "📋 Исходные данные",
        "view_data": "Посмотреть данные",
        "merged_data": "Посмотреть объединённые данные",
        "export_data": "💾 Экспорт данных",
        "download": "📥 Скачать",
        "loading_data": "Загрузка данных...",
        "error_loading": "Невозможно загрузить данные. Попробуйте позже.",
        "error_fetching": "Ошибка при загрузке",
        "economic_analysis": "🌍 Экономический Анализ по Континентам",
        "select_continent": "Выберите континент",
        "generate_analysis": "Создать анализ",
        "analysis_disclaimer": "Этот анализ создан ИИ и не является финансовой рекомендацией.",
        "loading_analysis": "Генерация экономического анализа...",
        "api_key_required": "Требуется API ключ",
        "api_key_help": "Получите бесплатный API ключ на",
        "enter_api_key": "Введите ваш Groq API ключ",
        "analysis_error": "Ошибка при генерации анализа. Проверьте API ключ и попробуйте снова.",
        "continents": {
            "north_america": "Северная Америка",
            "south_america": "Южная Америка",
            "europe": "Европа",
            "asia": "Азия",
            "africa": "Африка",
            "oceania": "Океания"
        },
        "economic_indicators": "Ключевые Экономические Показатели",
        "ai_analysis": "ИИ Экономический Анализ",
        "last_analysis": "Анализ создан",
        "credit_risk": "🏦 Анализ Кредитного Риска",
        "credit_risk_title": "Анализ Кредитного Риска",
        "enter_ticker": "Введите тикер",
        "analyze_button": "Анализировать Кредитный Риск",
        "merton_model": "Структурная Модель Мертона",
        "ml_model": "ML Модель (Историческая)",
        "distance_to_default": "Расстояние до Дефолта",
        "probability_of_default": "Вероятность Дефолта",
        "risk_category": "Категория Риска",
        "very_low_risk": "Очень Низкий Риск",
        "low_risk": "Низкий Риск",
        "moderate_risk": "Умеренный Риск",
        "high_risk": "Высокий Риск",
        "very_high_risk": "Очень Высокий Риск",
        "model_inputs": "Входные Данные Модели",
        "market_cap": "Рыночная Капитализация",
        "total_debt": "Общий Долг",
        "asset_value": "Стоимость Активов (V)",
        "equity_volatility": "Волатильность Акций",
        "risk_free_rate": "Безрисковая Ставка",
        "time_horizon": "Временной Горизонт",
        "merton_explanation": "Модель Мертона рассматривает капитал как колл-опцион на активы компании.",
        "ml_explanation": "ML модель обучена на исторических данных о банкротстве (1999-2018).",
        "data_unavailable": "Необходимые финансовые данные недоступны для этого тикера.",
        "analyzing": "Анализ кредитного риска...",
        "credit_risk_comparison": "Сравнение Кредитного Риска",
        "benchmark_companies": "Эталонные Компании",
    },
    
    "العربية": {
        "page_title": "لوحة المعلومات المالية",
        "main_title": "📈 لوحة المعلومات المالية",
        "comparison": "مقارنة",
        "vs": "مقابل",
        "years": "سنوات",
        "over": "خلال",
        "settings": "⚙️ الإعدادات",
        "language": "🌐 اللغة",
        "asset_selection": "اختيار الأصول",
        "first_asset": "الأصل الأول",
        "second_asset": "الأصل الثاني",
        "period": "الفترة",
        "num_years": "عدد السنوات",
        "display_options": "خيارات العرض",
        "show_normalized": "عرض الأسعار المعيارية",
        "show_drawdown": "عرض التراجعات",
        "show_volume": "عرض أحجام التداول",
        "refresh_data": "🔄 تحديث البيانات",
        "last_update": "آخر تحديث",
        "created_with": "لوحة معلومات تم إنشاؤها باستخدام Streamlit",
        "cryptocurrencies": "العملات المشفرة",
        "indices": "المؤشرات",
        "tech_stocks": "أسهم التكنولوجيا",
        "commodities": "السلع",
        "key_metrics": "📊 المؤشرات الرئيسية",
        "return": "العائد",
        "volatility": "التقلب",
        "current_price": "السعر الحالي",
        "sharpe": "شارب",
        "performance_comparison": "📈 مقارنة الأداء",
        "normalized_prices": "الأسعار المعيارية",
        "prices": "الأسعار",
        "normalized_price_zscore": "السعر المعياري (z-score)",
        "price_usd": "السعر ($)",
        "date": "التاريخ",
        "asset": "الأصل",
        "drawdowns_title": "📉 التراجعات (الخسائر من الذروة)",
        "drawdowns_from_ath": "التراجعات من أعلى المستويات التاريخية",
        "max_drawdown": "أقصى تراجع",
        "trading_volumes": "📊 أحجام التداول",
        "volume": "الحجم",
        "correlation_analysis": "🔗 تحليل الارتباط",
        "overall_correlation": "الارتباط الكلي",
        "rolling_correlation": "الارتباط المتحرك",
        "days": "يوم",
        "interpretation": "التفسير",
        "strong_positive": "ارتباط إيجابي قوي",
        "moderate": "ارتباط معتدل",
        "weak": "ارتباط ضعيف",
        "negative": "ارتباط سلبي",
        "recent_news": "📰 آخر الأخبار",
        "no_news": "لا توجد أخبار متاحة",
        "raw_data": "📋 البيانات الخام",
        "view_data": "عرض البيانات",
        "merged_data": "عرض البيانات المدمجة",
        "export_data": "💾 تصدير البيانات",
        "download": "📥 تحميل",
        "loading_data": "جاري تحميل البيانات...",
        "error_loading": "تعذر تحميل البيانات. يرجى المحاولة مرة أخرى لاحقاً.",
        "error_fetching": "خطأ في جلب",
        "economic_analysis": "🌍 التحليل الاقتصادي حسب القارة",
        "select_continent": "اختر قارة",
        "generate_analysis": "إنشاء التحليل",
        "analysis_disclaimer": "هذا التحليل تم إنشاؤه بواسطة الذكاء الاصطناعي ولا ينبغي اعتباره نصيحة مالية.",
        "loading_analysis": "جاري إنشاء التحليل الاقتصادي...",
        "api_key_required": "مفتاح API مطلوب",
        "api_key_help": "احصل على مفتاح API المجاني من",
        "enter_api_key": "أدخل مفتاح Groq API الخاص بك",
        "analysis_error": "خطأ في إنشاء التحليل. يرجى التحقق من مفتاح API والمحاولة مرة أخرى.",
        "continents": {
            "north_america": "أمريكا الشمالية",
            "south_america": "أمريكا الجنوبية",
            "europe": "أوروبا",
            "asia": "آسيا",
            "africa": "أفريقيا",
            "oceania": "أوقيانوسيا"
        },
        "economic_indicators": "المؤشرات الاقتصادية الرئيسية",
        "ai_analysis": "التحليل الاقتصادي بالذكاء الاصطناعي",
        "last_analysis": "تم إنشاء التحليل في",
        "credit_risk": "🏦 تحليل مخاطر الائتمان",
        "credit_risk_title": "تحليل مخاطر الائتمان",
        "enter_ticker": "أدخل رمز السهم",
        "analyze_button": "تحليل مخاطر الائتمان",
        "merton_model": "نموذج ميرتون الهيكلي",
        "ml_model": "نموذج التعلم الآلي (تاريخي)",
        "distance_to_default": "المسافة إلى التخلف عن السداد",
        "probability_of_default": "احتمال التخلف عن السداد",
        "risk_category": "فئة المخاطر",
        "very_low_risk": "مخاطر منخفضة جداً",
        "low_risk": "مخاطر منخفضة",
        "moderate_risk": "مخاطر معتدلة",
        "high_risk": "مخاطر عالية",
        "very_high_risk": "مخاطر عالية جداً",
        "model_inputs": "مدخلات النموذج",
        "market_cap": "القيمة السوقية",
        "total_debt": "إجمالي الديون",
        "asset_value": "قيمة الأصول (V)",
        "equity_volatility": "تقلب الأسهم",
        "risk_free_rate": "معدل خالي من المخاطر",
        "time_horizon": "الأفق الزمني",
        "merton_explanation": "يعامل نموذج ميرتون حقوق الملكية كخيار شراء على أصول الشركة.",
        "ml_explanation": "نموذج ML مدرب على بيانات الإفلاس التاريخية (1999-2018).",
        "data_unavailable": "البيانات المالية المطلوبة غير متوفرة لهذا الرمز.",
        "analyzing": "جاري تحليل مخاطر الائتمان...",
        "credit_risk_comparison": "مقارنة مخاطر الائتمان",
        "benchmark_companies": "الشركات المرجعية",
    },
}

# Language configuration (RTL support)
RTL_LANGUAGES = ["العربية"]

def get_text(key: str) -> str:
    """Get translated text for the current language."""
    lang = st.session_state.get("language", "English")
    return TRANSLATIONS.get(lang, TRANSLATIONS["English"]).get(key, key)

def t(key: str) -> str:
    """Shorthand for get_text."""
    return get_text(key)


# =============================================================================
# PAGE CONFIGURATION
# =============================================================================
st.set_page_config(
    page_title="Financial Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =============================================================================
# SESSION STATE INITIALIZATION
# =============================================================================
if "language" not in st.session_state:
    st.session_state.language = "English"


# =============================================================================
# CUSTOM CSS
# =============================================================================
def apply_custom_css():
    """Apply custom CSS including RTL support and professional parchment theme."""
    is_rtl = st.session_state.language in RTL_LANGUAGES
    direction = "rtl" if is_rtl else "ltr"
    text_align = "right" if is_rtl else "left"
    
    st.markdown(f"""
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&family=Source+Sans+Pro:wght@400;600;700&display=swap');
        
        .stApp {{
            background: linear-gradient(135deg, #F5E6C8 0%, #EDE0C8 50%, #F0E4CE 100%);
            font-family: 'Source Sans Pro', sans-serif;
        }}
        
        .main .block-container {{
            direction: {direction};
            text-align: {text_align};
            padding-top: 2rem;
            max-width: 1200px;
        }}
        
        h1 {{
            font-family: 'Libre Baskerville', serif !important;
            color: #4A3728 !important;
            font-weight: 700 !important;
            letter-spacing: 0.5px;
            border-bottom: 3px solid #8B7355;
            padding-bottom: 0.5rem;
            margin-bottom: 1.5rem !important;
        }}
        
        h2 {{
            font-family: 'Libre Baskerville', serif !important;
            color: #5D4E37 !important;
            font-weight: 700 !important;
            font-size: 1.5rem !important;
            margin-top: 1rem !important;
            padding-left: 0.5rem;
            border-left: 4px solid #8B7355;
        }}
        
        h3 {{
            font-family: 'Source Sans Pro', sans-serif !important;
            color: #6B5B4A !important;
            font-weight: 600 !important;
            font-size: 1.1rem !important;
            text-transform: uppercase;
            letter-spacing: 1px;
        }}
        
        p, span, label {{
            color: #4A3F35 !important;
        }}
        
        /* Global fix for all text content */
        div[data-testid="stMarkdownContainer"] p,
        div[data-testid="stMarkdownContainer"] span,
        div[data-testid="stMarkdownContainer"] li,
        div[data-testid="stMarkdownContainer"] strong {{
            color: #3D3428 !important;
        }}
        
        /* Fix any div text that might be invisible */
        .main div {{
            color: #3D3428;
        }}
        
        [data-testid="stSidebar"] {{
            background: linear-gradient(180deg, #E8D9BE 0%, #DFD0B8 100%);
            border-right: 1px solid #C4B59B;
            box-shadow: 2px 0 10px rgba(74, 55, 40, 0.1);
        }}
        
        [data-testid="stMetric"] {{
            background: linear-gradient(145deg, #FFFEFA 0%, #FBF6ED 100%);
            padding: 1.25rem 1.5rem;
            border-radius: 12px;
            border: 1px solid #D4C5A9;
            box-shadow: 0 4px 15px rgba(74, 55, 40, 0.08);
            transition: all 0.3s ease;
        }}
        
        [data-testid="stMetric"]:hover {{
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(74, 55, 40, 0.12);
        }}
        
        /* Fix metric label visibility */
        [data-testid="stMetric"] label {{
            color: #5D4E37 !important;
        }}
        
        /* Fix metric VALUE visibility - this is the main fix */
        [data-testid="stMetric"] [data-testid="stMetricValue"] {{
            color: #2D2418 !important;
        }}
        
        [data-testid="stMetric"] [data-testid="stMetricValue"] div {{
            color: #2D2418 !important;
        }}
        
        /* Fix metric delta visibility */
        [data-testid="stMetric"] [data-testid="stMetricDelta"] {{
            color: #3D3428 !important;
        }}
        
        [data-testid="stMetric"] [data-testid="stMetricDelta"] svg {{
            fill: #3D3428 !important;
        }}
        
        .stButton > button {{
            background: linear-gradient(145deg, #FFFEFA 0%, #F5EFE0 100%);
            color: #4A3F35 !important;
            border: 2px solid #B8A88A;
            border-radius: 10px;
            padding: 0.7rem 1.5rem;
            font-weight: 600;
            transition: all 0.3s ease;
        }}
        
        .stButton > button:hover {{
            background: linear-gradient(145deg, #F5EFE0 0%, #EDE5D3 100%);
            border-color: #8B7355;
            transform: translateY(-1px);
        }}
        
        [data-testid="stExpander"] {{
            background-color: #FFFEFA;
            border: 1px solid #D4C5A9;
            border-radius: 10px;
        }}
        
        /* Fix expander content text visibility */
        [data-testid="stExpander"] [data-testid="stMarkdownContainer"] {{
            color: #3D3428 !important;
        }}
        
        [data-testid="stExpander"] [data-testid="stMarkdownContainer"] p {{
            color: #3D3428 !important;
        }}
        
        [data-testid="stExpander"] [data-testid="stMarkdownContainer"] li {{
            color: #3D3428 !important;
        }}
        
        [data-testid="stExpander"] [data-testid="stMarkdownContainer"] strong {{
            color: #2D2418 !important;
        }}
        
        [data-testid="stExpander"] summary {{
            color: #3D3428 !important;
        }}
        
        [data-testid="stExpander"] summary span {{
            color: #3D3428 !important;
        }}
        
        [data-testid="stPlotlyChart"] {{
            background-color: #FFFEFA;
            border-radius: 12px;
            padding: 1rem;
            box-shadow: 0 4px 15px rgba(74, 55, 40, 0.08);
            border: 1px solid #E8DCC8;
        }}
        
        /* Download button styling - light background with dark text */
        .stDownloadButton > button {{
            background: linear-gradient(145deg, #FFFEFA 0%, #F5EFE0 100%) !important;
            color: #3D3428 !important;
            border: 2px solid #B8A88A !important;
            border-radius: 10px;
            padding: 0.7rem 1.5rem;
            font-weight: 600;
            transition: all 0.3s ease;
        }}
        
        .stDownloadButton > button:hover {{
            background: linear-gradient(145deg, #F5EFE0 0%, #EDE5D3 100%) !important;
            border-color: #8B7355 !important;
            transform: translateY(-1px);
        }}
        
        .stDownloadButton > button span,
        .stDownloadButton > button p {{
            color: #3D3428 !important;
        }}
        
        .risk-gauge {{
            text-align: center;
            padding: 1rem;
            border-radius: 10px;
            margin: 0.5rem 0;
        }}
        
        .risk-very-low {{ background-color: #d4edda; border: 2px solid #28a745; }}
        .risk-low {{ background-color: #d1ecf1; border: 2px solid #17a2b8; }}
        .risk-moderate {{ background-color: #fff3cd; border: 2px solid #ffc107; }}
        .risk-high {{ background-color: #f8d7da; border: 2px solid #dc3545; }}
        .risk-very-high {{ background-color: #721c24; border: 2px solid #721c24; color: white; }}
    </style>
    """, unsafe_allow_html=True)

apply_custom_css()


# =============================================================================
# CONSTANTS AND CONFIGURATION
# =============================================================================
ASSETS = {
    "cryptocurrencies": {
        "BTC-USD": "Bitcoin",
        "ETH-USD": "Ethereum",
        "SOL-USD": "Solana",
        "BNB-USD": "Binance Coin"
    },
    "indices": {
        "^GSPC": "S&P 500",
        "^IXIC": "NASDAQ",
        "^DJI": "Dow Jones",
        "^FCHI": "CAC 40",
        "^STOXX50E": "Euro Stoxx 50"
    },
    "tech_stocks": {
        "AAPL": "Apple",
        "MSFT": "Microsoft",
        "GOOGL": "Google",
        "NVDA": "NVIDIA",
        "META": "Meta"
    },
    "commodities": {
        "GC=F": "Gold",
        "SI=F": "Silver",
        "CL=F": "Oil (WTI)"
    }
}

ALL_ASSETS = {}
for category, assets in ASSETS.items():
    ALL_ASSETS.update(assets)

TICKER_TO_NAME = {ticker: name for ticker, name in ALL_ASSETS.items()}
NAME_TO_TICKER = {name: ticker for ticker, name in ALL_ASSETS.items()}


# =============================================================================
# DATA LOADING FUNCTIONS
# =============================================================================
@st.cache_data(ttl=3600)
def load_asset_data(ticker: str, years: int) -> pd.DataFrame:
    """Load historical data for an asset."""
    today = datetime.today()
    start_date = today - timedelta(days=365 * years)
    
    try:
        data = yf.Ticker(ticker).history(start=start_date, end=today)
        if data.empty:
            return pd.DataFrame()
        
        df = pd.DataFrame(data)
        df.reset_index(inplace=True)
        df['Date'] = pd.to_datetime(df['Date']).dt.date
        return df
    except Exception as e:
        st.error(f"{t('error_fetching')} {ticker}: {e}")
        return pd.DataFrame()


@st.cache_data(ttl=3600)
def get_asset_info(ticker: str) -> dict:
    """Get detailed asset information."""
    try:
        info = yf.Ticker(ticker).info
        return info
    except:
        return {}


def normalize_series(series: pd.Series) -> pd.Series:
    """Normalize a series (z-score)."""
    return (series - series.mean()) / series.std()


def calculate_returns(prices: pd.Series) -> float:
    """Calculate total return in percentage."""
    if len(prices) < 2:
        return 0.0
    return ((prices.iloc[-1] / prices.iloc[0]) - 1) * 100


def calculate_volatility(prices: pd.Series, annualize: bool = True) -> float:
    """Calculate volatility (standard deviation of returns)."""
    returns = prices.pct_change().dropna()
    vol = returns.std()
    if annualize:
        vol *= np.sqrt(252)
    return vol * 100


def calculate_drawdown(prices: pd.Series) -> pd.Series:
    """Calculate drawdown from all-time high."""
    peak = prices.cummax()
    drawdown = (prices - peak) / peak * 100
    return drawdown


def calculate_sharpe_ratio(prices: pd.Series, risk_free_rate: float = 0.04) -> float:
    """Calculate simplified Sharpe ratio."""
    returns = prices.pct_change().dropna()
    excess_return = returns.mean() * 252 - risk_free_rate
    volatility = returns.std() * np.sqrt(252)
    if volatility == 0:
        return 0
    return excess_return / volatility


@st.cache_data(ttl=3600)
def get_news(ticker: str) -> list:
    """Get news via Yahoo Finance RSS."""
    try:
        feed = feedparser.parse(f"https://feeds.finance.yahoo.com/rss/2.0/headline?s={ticker}")
        return feed.entries[:5]
    except:
        return []


# =============================================================================
# CREDIT RISK FUNCTIONS (MERTON MODEL)
# =============================================================================
def calculate_distance_to_default(V: float, D: float, sigma_V: float, r: float, T: float) -> float:
    """
    Calculate distance to default using Merton model.
    
    Parameters:
    -----------
    V : float - Asset value (market cap + debt proxy)
    D : float - Debt face value (default barrier)
    sigma_V : float - Asset volatility (annualized, as decimal)
    r : float - Risk-free rate (as decimal)
    T : float - Time horizon (years)
    
    Returns:
    --------
    float - Distance to default (in standard deviations)
    """
    if D <= 0 or V <= 0 or sigma_V <= 0 or T <= 0:
        return 0.0
    
    numerator = np.log(V / D) + (r - 0.5 * sigma_V**2) * T
    denominator = sigma_V * np.sqrt(T)
    
    return numerator / denominator


def calculate_probability_of_default(DD: float) -> float:
    """
    Convert distance to default to probability of default.
    
    Parameters:
    -----------
    DD : float - Distance to default
    
    Returns:
    --------
    float - Probability of default (0 to 1)
    """
    return norm.cdf(-DD)


def get_risk_category(pd_value: float) -> tuple:
    """
    Categorize risk based on probability of default.
    
    Returns:
    --------
    tuple - (category_key, css_class)
    """
    if pd_value < 0.01:
        return ("very_low_risk", "risk-very-low")
    elif pd_value < 0.05:
        return ("low_risk", "risk-low")
    elif pd_value < 0.15:
        return ("moderate_risk", "risk-moderate")
    elif pd_value < 0.30:
        return ("high_risk", "risk-high")
    else:
        return ("very_high_risk", "risk-very-high")


@st.cache_data(ttl=1800)
def get_credit_risk_data(ticker: str) -> dict:
    """
    Fetch all data needed for credit risk analysis.
    
    Returns:
    --------
    dict with keys: market_cap, total_debt, cash, equity_volatility, company_name, success
    """
    try:
        stock = yf.Ticker(ticker)
        info = stock.info
        
        # Get market cap
        market_cap = info.get('marketCap', None)
        
        # Get balance sheet data
        balance_sheet = stock.balance_sheet
        
        total_debt = None
        cash = None
        
        if not balance_sheet.empty:
            bs = balance_sheet.T
            if 'Total Debt' in bs.columns:
                total_debt = bs['Total Debt'].iloc[0]
            if 'Cash Cash Equivalents And Short Term Investments' in bs.columns:
                cash = bs['Cash Cash Equivalents And Short Term Investments'].iloc[0]
            elif 'Cash And Cash Equivalents' in bs.columns:
                cash = bs['Cash And Cash Equivalents'].iloc[0]
        
        # Calculate equity volatility from historical prices
        hist = stock.history(period="2y")
        if not hist.empty and len(hist) > 20:
            log_returns = np.log(hist['Close'] / hist['Close'].shift(1)).dropna()
            daily_vol = log_returns.std()
            annual_vol = daily_vol * np.sqrt(252)
        else:
            annual_vol = None
        
        company_name = info.get('longName', info.get('shortName', ticker))
        
        return {
            'market_cap': market_cap,
            'total_debt': total_debt,
            'cash': cash,
            'equity_volatility': annual_vol,
            'company_name': company_name,
            'success': market_cap is not None and total_debt is not None and annual_vol is not None
        }
    except Exception as e:
        return {'success': False, 'error': str(e)}


# =============================================================================
# AI ECONOMIC ANALYSIS FUNCTIONS
# =============================================================================
CONTINENT_INDICATORS = {
    "north_america": {
        "indices": ["^GSPC", "^DJI", "^IXIC", "^GSPTSE"],
        "names": ["S&P 500", "Dow Jones", "NASDAQ", "TSX (Canada)"],
        "countries": ["USA", "Canada", "Mexico"]
    },
    "south_america": {
        "indices": ["^BVSP", "^MERV", "^IPSA"],
        "names": ["Bovespa (Brazil)", "MERVAL (Argentina)", "IPSA (Chile)"],
        "countries": ["Brazil", "Argentina", "Chile", "Colombia"]
    },
    "europe": {
        "indices": ["^STOXX50E", "^FTSE", "^GDAXI", "^FCHI"],
        "names": ["Euro Stoxx 50", "FTSE 100", "DAX", "CAC 40"],
        "countries": ["Germany", "UK", "France", "Italy", "Spain"]
    },
    "asia": {
        "indices": ["^N225", "^HSI", "000001.SS", "^BSESN"],
        "names": ["Nikkei 225", "Hang Seng", "Shanghai", "BSE Sensex"],
        "countries": ["Japan", "China", "India", "South Korea", "Singapore"]
    },
    "africa": {
        "indices": ["^JN0U.JO", "EGX30.CA"],
        "names": ["JSE Top 40 (South Africa)", "EGX 30 (Egypt)"],
        "countries": ["South Africa", "Egypt", "Nigeria", "Kenya"]
    },
    "oceania": {
        "indices": ["^AXJO", "^NZ50"],
        "names": ["ASX 200 (Australia)", "NZX 50 (New Zealand)"],
        "countries": ["Australia", "New Zealand"]
    }
}


def get_continent_data(continent_key: str) -> dict:
    """Fetch recent performance data for continent indices."""
    indicators = CONTINENT_INDICATORS.get(continent_key, {})
    results = {}
    
    for ticker, name in zip(indicators.get("indices", []), indicators.get("names", [])):
        try:
            data = yf.Ticker(ticker).history(period="1mo")
            if not data.empty:
                current = data['Close'].iloc[-1]
                month_ago = data['Close'].iloc[0]
                change_pct = ((current - month_ago) / month_ago) * 100
                results[name] = {
                    "current": current,
                    "change_1m": change_pct
                }
        except:
            continue
    
    return results


def generate_economic_analysis(continent_key: str, continent_name: str, api_key: str, language: str = "English") -> str:
    """Generate economic analysis using Groq API with Llama 3."""
    
    market_data = get_continent_data(continent_key)
    indicators = CONTINENT_INDICATORS.get(continent_key, {})
    
    market_context = ""
    for name, data in market_data.items():
        direction = "up" if data["change_1m"] > 0 else "down"
        market_context += f"- {name}: {data['current']:.2f} ({direction} {abs(data['change_1m']):.1f}% this month)\n"
    
    countries = ", ".join(indicators.get("countries", []))
    
    lang_instruction = {
        "English": "Respond in English.",
        "Français": "Réponds en français.",
        "Español": "Responde en español.",
        "中文": "请用中文回复。",
        "Русский": "Отвечай на русском языке.",
        "العربية": "الرجاء الرد باللغة العربية."
    }.get(language, "Respond in English.")
    
    prompt = f"""{lang_instruction}

You are an expert economic analyst. Provide a comprehensive but concise analysis of the current economic state of {continent_name}.

Current Market Data:
{market_context}

Major economies in this region: {countries}

Please provide:
1. **Overall Economic Health** (2-3 sentences)
2. **Key Trends** (3-4 bullet points on current economic trends)
3. **Challenges** (2-3 main challenges facing the region)
4. **Opportunities** (2-3 investment or growth opportunities)
5. **Short-term Outlook** (1-2 sentences on what to expect in the next 3-6 months)

Keep the analysis factual, balanced, and around 300-400 words total."""

    try:
        response = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            },
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [
                    {"role": "system", "content": "You are a professional economic analyst."},
                    {"role": "user", "content": prompt}
                ],
                "temperature": 0.7,
                "max_tokens": 1000
            },
            timeout=30
        )
        
        if response.status_code == 200:
            return response.json()["choices"][0]["message"]["content"]
        else:
            return None
            
    except Exception as e:
        return None


# =============================================================================
# SIDEBAR
# =============================================================================
with st.sidebar:
    st.subheader(t("language"))
    language = st.selectbox(
        "Language",
        options=list(TRANSLATIONS.keys()),
        index=list(TRANSLATIONS.keys()).index(st.session_state.language),
        label_visibility="collapsed"
    )
    
    if language != st.session_state.language:
        st.session_state.language = language
        st.rerun()
    
    st.markdown("---")
    st.header(t("settings"))
    
    st.subheader(t("asset_selection"))
    
    asset1_name = st.selectbox(
        t("first_asset"),
        options=list(NAME_TO_TICKER.keys()),
        index=list(NAME_TO_TICKER.keys()).index("Bitcoin")
    )
    asset1_ticker = NAME_TO_TICKER[asset1_name]
    
    asset2_name = st.selectbox(
        t("second_asset"),
        options=list(NAME_TO_TICKER.keys()),
        index=list(NAME_TO_TICKER.keys()).index("S&P 500")
    )
    asset2_ticker = NAME_TO_TICKER[asset2_name]
    
    st.subheader(t("period"))
    years = st.slider(t("num_years"), min_value=1, max_value=10, value=5)
    
    st.subheader(t("display_options"))
    show_normalized = st.checkbox(t("show_normalized"), value=True)
    show_drawdown = st.checkbox(t("show_drawdown"), value=True)
    show_volume = st.checkbox(t("show_volume"), value=False)
    
    st.markdown("---")
    
    if st.button(t("refresh_data"), use_container_width=True):
        st.cache_data.clear()
        st.rerun()
    
    st.markdown("---")
    st.caption(t("created_with"))
    st.caption(f"{t('last_update')}: {datetime.now().strftime('%H:%M:%S')}")


# =============================================================================
# MAIN CONTENT WITH TABS
# =============================================================================
st.title(t("main_title"))

# Create tabs
tab_comparison, tab_economic, tab_credit = st.tabs([
    f"📊 {t('performance_comparison')}", 
    f"🌍 {t('economic_analysis')}",
    f"🏦 {t('credit_risk')}"
])

# =============================================================================
# TAB 1: ASSET COMPARISON
# =============================================================================
with tab_comparison:
    st.markdown(f"**{t('comparison')}:** {asset1_name} {t('vs')} {asset2_name} {t('over')} {years} {t('years')}")
    
    with st.spinner(t("loading_data")):
        df1 = load_asset_data(asset1_ticker, years)
        df2 = load_asset_data(asset2_ticker, years)
    
    if df1.empty or df2.empty:
        st.error(t("error_loading"))
        st.stop()
    
    # Key Metrics
    st.header(t("key_metrics"))
    
    col1, col2, col3, col4 = st.columns(4)
    
    return1 = calculate_returns(df1['Close'])
    with col1:
        st.metric(label=f"{t('return')} {asset1_name}", value=f"{return1:.1f}%",
                  delta=f"{return1:.1f}%" if return1 != 0 else None)
    
    return2 = calculate_returns(df2['Close'])
    with col2:
        st.metric(label=f"{t('return')} {asset2_name}", value=f"{return2:.1f}%",
                  delta=f"{return2:.1f}%" if return2 != 0 else None)
    
    vol1 = calculate_volatility(df1['Close'])
    with col3:
        st.metric(label=f"{t('volatility')} {asset1_name}", value=f"{vol1:.1f}%")
    
    vol2 = calculate_volatility(df2['Close'])
    with col4:
        st.metric(label=f"{t('volatility')} {asset2_name}", value=f"{vol2:.1f}%")
    
    col5, col6, col7, col8 = st.columns(4)
    
    with col5:
        st.metric(label=f"{t('current_price')} {asset1_name}", value=f"${df1['Close'].iloc[-1]:,.2f}")
    
    with col6:
        st.metric(label=f"{t('current_price')} {asset2_name}", value=f"${df2['Close'].iloc[-1]:,.2f}")
    
    with col7:
        st.metric(label=f"{t('sharpe')} {asset1_name}", value=f"{calculate_sharpe_ratio(df1['Close']):.2f}")
    
    with col8:
        st.metric(label=f"{t('sharpe')} {asset2_name}", value=f"{calculate_sharpe_ratio(df2['Close']):.2f}")
    
    # Main Chart
    st.markdown("---")
    st.header(t("performance_comparison"))
    
    df1_plot = df1[['Date', 'Close']].copy()
    df2_plot = df2[['Date', 'Close']].copy()
    
    if show_normalized:
        df1_plot['Close'] = normalize_series(df1['Close'])
        df2_plot['Close'] = normalize_series(df2['Close'])
        y_label = t("normalized_price_zscore")
    else:
        y_label = t("price_usd")
    
    df1_plot = df1_plot.rename(columns={'Close': asset1_name})
    df2_plot = df2_plot.rename(columns={'Close': asset2_name})
    
    merged = pd.merge(df1_plot, df2_plot, on='Date', how='inner')
    merged_melted = merged.melt(id_vars=['Date'], var_name=t('asset'), value_name=t('prices'))
    
    chart_title = f"{t('normalized_prices') if show_normalized else t('prices')}: {asset1_name} {t('vs')} {asset2_name}"
    fig_main = px.line(merged_melted, x='Date', y=t('prices'), color=t('asset'), title=chart_title,
                       color_discrete_map={asset1_name: '#C45B28', asset2_name: '#1B6B4A'},
                       template='plotly_white')
    
    fig_main.update_layout(
        xaxis_title=t("date"), yaxis_title=y_label,
        hovermode="x unified", height=450,
        paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='#FFFEFA',
        font=dict(family="Source Sans Pro, sans-serif", color='#2D2418', size=12),
        title=dict(font=dict(color='#2D2418', size=16)),
        legend=dict(
            orientation="h", yanchor="bottom", y=1.02, xanchor="center", x=0.5,
            font=dict(color='#2D2418', size=12),
            bgcolor='rgba(255,254,250,0.9)'
        ),
        xaxis=dict(tickfont=dict(color='#3D3428')),
        yaxis=dict(tickfont=dict(color='#3D3428'))
    )
    fig_main.update_traces(line=dict(width=2.5))
    st.plotly_chart(fig_main, use_container_width=True)
    
    # Drawdown Chart
    if show_drawdown:
        st.markdown("---")
        st.header(t("drawdowns_title"))
        
        df1['Drawdown'] = calculate_drawdown(df1['Close'])
        df2['Drawdown'] = calculate_drawdown(df2['Close'])
        
        fig_dd = go.Figure()
        fig_dd.add_trace(go.Scatter(x=df1['Date'], y=df1['Drawdown'], fill='tozeroy', name=asset1_name,
                                     line=dict(color='#C45B28', width=2), fillcolor='rgba(196, 91, 40, 0.25)'))
        fig_dd.add_trace(go.Scatter(x=df2['Date'], y=df2['Drawdown'], fill='tozeroy', name=asset2_name,
                                     line=dict(color='#1B6B4A', width=2), fillcolor='rgba(27, 107, 74, 0.25)'))
        
        fig_dd.update_layout(
            title=dict(text=t("drawdowns_from_ath"), font=dict(color='#2D2418', size=16)),
            xaxis_title=t("date"), yaxis_title="Drawdown (%)",
            template='plotly_white', height=350, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='#FFFEFA',
            font=dict(family="Source Sans Pro, sans-serif", color='#2D2418', size=12),
            legend=dict(
                orientation="h", yanchor="bottom", y=1.02, xanchor="center", x=0.5,
                font=dict(color='#2D2418', size=12),
                bgcolor='rgba(255,254,250,0.9)'
            ),
            xaxis=dict(tickfont=dict(color='#3D3428')),
            yaxis=dict(tickfont=dict(color='#3D3428'))
        )
        st.plotly_chart(fig_dd, use_container_width=True)
        
        col_dd1, col_dd2 = st.columns(2)
        with col_dd1:
            st.metric(f"{t('max_drawdown')} {asset1_name}", f"{df1['Drawdown'].min():.1f}%")
        with col_dd2:
            st.metric(f"{t('max_drawdown')} {asset2_name}", f"{df2['Drawdown'].min():.1f}%")
    
    # Volume Chart
    if show_volume:
        st.markdown("---")
        st.header(t("trading_volumes"))
        
        fig_vol = make_subplots(rows=2, cols=1, shared_xaxes=True,
                                subplot_titles=(f"{t('volume')} {asset1_name}", f"{t('volume')} {asset2_name}"))
        fig_vol.add_trace(go.Bar(x=df1['Date'], y=df1['Volume'], name=asset1_name, marker=dict(color='#C45B28')), row=1, col=1)
        fig_vol.add_trace(go.Bar(x=df2['Date'], y=df2['Volume'], name=asset2_name, marker=dict(color='#1B6B4A')), row=2, col=1)
        
        fig_vol.update_layout(height=450, template='plotly_white', showlegend=False,
                              paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='#FFFEFA',
                              font=dict(family="Source Sans Pro, sans-serif", color='#2D2418', size=12))
        fig_vol.update_xaxes(tickfont=dict(color='#3D3428'))
        fig_vol.update_yaxes(tickfont=dict(color='#3D3428'))
        fig_vol.update_annotations(font=dict(color='#2D2418', size=14))
        st.plotly_chart(fig_vol, use_container_width=True)
    
    # Correlation
    st.markdown("---")
    st.header(t("correlation_analysis"))
    
    merged_corr = pd.merge(df1[['Date', 'Close']].rename(columns={'Close': 'Asset1'}),
                           df2[['Date', 'Close']].rename(columns={'Close': 'Asset2'}), on='Date', how='inner')
    merged_corr['Return1'] = merged_corr['Asset1'].pct_change()
    merged_corr['Return2'] = merged_corr['Asset2'].pct_change()
    merged_corr['Rolling_Corr'] = merged_corr['Return1'].rolling(window=30).corr(merged_corr['Return2'])
    
    col_corr1, col_corr2 = st.columns([1, 2])
    
    with col_corr1:
        overall_corr = merged_corr['Return1'].corr(merged_corr['Return2'])
        st.metric(t("overall_correlation"), f"{overall_corr:.3f}")
        st.markdown(f"""**{t('interpretation')}:**
        - **> 0.7**: {t('strong_positive')}
        - **0.3 - 0.7**: {t('moderate')}
        - **-0.3 - 0.3**: {t('weak')}
        - **< -0.3**: {t('negative')}""")
    
    with col_corr2:
        fig_corr = px.line(merged_corr, x='Date', y='Rolling_Corr', title=f"{t('rolling_correlation')} (30 {t('days')})")
        fig_corr.add_hline(y=0, line_dash="dash", line_color="#8B7355")
        fig_corr.update_traces(line=dict(color='#C45B28', width=2.5))
        fig_corr.update_layout(
            yaxis_title=t("overall_correlation"), height=300,
            paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='#FFFEFA',
            font=dict(family="Source Sans Pro, sans-serif", color='#2D2418', size=12),
            title=dict(font=dict(color='#2D2418', size=14)),
            xaxis=dict(tickfont=dict(color='#3D3428')),
            yaxis=dict(tickfont=dict(color='#3D3428'))
        )
        st.plotly_chart(fig_corr, use_container_width=True)
    
    # News
    st.markdown("---")
    st.header(t("recent_news"))
    
    col_news1, col_news2 = st.columns(2)
    
    with col_news1:
        st.subheader(f"📰 {asset1_name}")
        news1 = get_news(asset1_ticker)
        if news1:
            for entry in news1:
                st.markdown(f"**[{entry.title}]({entry.link})**")
                if hasattr(entry, 'published'):
                    st.caption(entry.published)
                st.markdown("---")
        else:
            st.info(t("no_news"))
    
    with col_news2:
        st.subheader(f"📰 {asset2_name}")
        news2 = get_news(asset2_ticker)
        if news2:
            for entry in news2:
                st.markdown(f"**[{entry.title}]({entry.link})**")
                if hasattr(entry, 'published'):
                    st.caption(entry.published)
                st.markdown("---")
        else:
            st.info(t("no_news"))
    
    # Raw Data & Export
    st.markdown("---")
    st.header(t("raw_data"))
    
    with st.expander(f"{t('view_data')} {asset1_name}"):
        st.dataframe(df1, use_container_width=True)
    
    with st.expander(f"{t('view_data')} {asset2_name}"):
        st.dataframe(df2, use_container_width=True)
    
    st.markdown("---")
    st.header(t("export_data"))
    
    col_export1, col_export2 = st.columns(2)
    with col_export1:
        st.download_button(label=f"{t('download')} {asset1_name} (CSV)", data=df1.to_csv(index=False),
                           file_name=f"{asset1_ticker}_{years}y.csv", mime="text/csv")
    with col_export2:
        st.download_button(label=f"{t('download')} {asset2_name} (CSV)", data=df2.to_csv(index=False),
                           file_name=f"{asset2_ticker}_{years}y.csv", mime="text/csv")


# =============================================================================
# TAB 2: ECONOMIC ANALYSIS
# =============================================================================
with tab_economic:
    st.markdown(f"*{t('analysis_disclaimer')}*")
    
    api_key_from_secrets = st.secrets.get("GROQ_API_KEY", None) if hasattr(st, 'secrets') else None
    
    if api_key_from_secrets:
        api_key = api_key_from_secrets
        st.success("✅ API Key loaded from secrets")
    else:
        st.subheader(t("api_key_required"))
        st.markdown(f"{t('api_key_help')} [console.groq.com](https://console.groq.com)")
        api_key = st.text_input(t("enter_api_key"), type="password")
    
    st.markdown("---")
    
    continents_dict = t("continents")
    if isinstance(continents_dict, dict):
        continent_options = list(continents_dict.values())
        continent_keys = list(continents_dict.keys())
    else:
        continent_options = ["North America", "South America", "Europe", "Asia", "Africa", "Oceania"]
        continent_keys = ["north_america", "south_america", "europe", "asia", "africa", "oceania"]
    
    selected_continent = st.selectbox(t("select_continent"), options=continent_options)
    selected_idx = continent_options.index(selected_continent)
    selected_key = continent_keys[selected_idx]
    
    st.subheader(t("economic_indicators"))
    market_data = get_continent_data(selected_key)
    
    if market_data:
        cols = st.columns(min(len(market_data), 4))
        for idx, (name, data) in enumerate(market_data.items()):
            with cols[idx % 4]:
                st.metric(label=name, value=f"{data['current']:,.2f}", delta=f"{data['change_1m']:+.1f}% (1M)")
    
    st.markdown("---")
    
    if st.button(t("generate_analysis"), use_container_width=True, disabled=not api_key):
        if api_key:
            with st.spinner(t("loading_analysis")):
                analysis = generate_economic_analysis(selected_key, selected_continent, api_key, st.session_state.language)
                if analysis:
                    st.subheader(t("ai_analysis"))
                    st.markdown(analysis)
                    st.caption(f"{t('last_analysis')}: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
                else:
                    st.error(t("analysis_error"))
    
    if not api_key:
        st.info("👆 " + t("api_key_required") + " " + t("api_key_help") + " [console.groq.com](https://console.groq.com)")


# =============================================================================
# TAB 3: CREDIT RISK ANALYSIS
# =============================================================================
with tab_credit:
    st.markdown(f"### {t('credit_risk_title')}")
    st.markdown(f"*{t('merton_explanation')}*")
    
    st.markdown("---")
    
    # Input section
    col_input1, col_input2 = st.columns([2, 1])
    
    with col_input1:
        ticker_input = st.text_input(t("enter_ticker"), value="AAPL", placeholder="e.g., AAPL, MSFT, BA")
    
    with col_input2:
        risk_free_rate = st.number_input(t("risk_free_rate"), min_value=0.0, max_value=0.20, value=0.045, step=0.005, format="%.3f")
        time_horizon = st.number_input(t("time_horizon"), min_value=0.5, max_value=5.0, value=1.0, step=0.5)
    
    analyze_button = st.button(t("analyze_button"), use_container_width=True, type="primary")
    
    if analyze_button and ticker_input:
        with st.spinner(t("analyzing")):
            data = get_credit_risk_data(ticker_input.upper())
            
            if data.get('success', False):
                # Calculate Merton model
                market_cap = data['market_cap']
                total_debt = data['total_debt']
                equity_vol = data['equity_volatility']
                company_name = data['company_name']
                
                # Asset value = Market Cap + Debt (simplified)
                V = market_cap + total_debt
                D = total_debt
                sigma_V = equity_vol  # Using equity vol as proxy (simplification)
                
                DD = calculate_distance_to_default(V, D, sigma_V, risk_free_rate, time_horizon)
                PD = calculate_probability_of_default(DD)
                risk_cat, risk_class = get_risk_category(PD)
                
                st.markdown("---")
                st.subheader(f"📊 {company_name} ({ticker_input.upper()})")
                
                # Results in columns
                col_res1, col_res2, col_res3 = st.columns(3)
                
                with col_res1:
                    st.metric(t("distance_to_default"), f"{DD:.2f}σ")
                
                with col_res2:
                    st.metric(t("probability_of_default"), f"{PD*100:.2f}%")
                
                with col_res3:
                    st.markdown(f"""
                    <div class="risk-gauge {risk_class}">
                        <strong>{t('risk_category')}</strong><br>
                        <span style="font-size: 1.5em;">{t(risk_cat)}</span>
                    </div>
                    """, unsafe_allow_html=True)
                
                # Model inputs display
                st.markdown("---")
                with st.expander(t("model_inputs")):
                    col_inp1, col_inp2, col_inp3 = st.columns(3)
                    
                    with col_inp1:
                        st.metric(t("market_cap"), f"${market_cap/1e9:.2f}B")
                        st.metric(t("total_debt"), f"${total_debt/1e9:.2f}B")
                    
                    with col_inp2:
                        st.metric(t("asset_value"), f"${V/1e9:.2f}B")
                        st.metric(t("equity_volatility"), f"{equity_vol*100:.1f}%")
                    
                    with col_inp3:
                        st.metric(t("risk_free_rate"), f"{risk_free_rate*100:.1f}%")
                        st.metric(t("time_horizon"), f"{time_horizon} {t('years')}")
                
                # Interpretation
                st.markdown("---")
                st.markdown(f"""
                **{t('interpretation')}:**
                
                - **{t('distance_to_default')}**: {DD:.2f}σ means the firm's asset value would need to fall by {DD:.2f} standard deviations to reach the default barrier.
                - **{t('probability_of_default')}**: Based on the Merton model, there is a **{PD*100:.2f}%** probability of default within {time_horizon} year(s).
                - A higher Distance to Default indicates lower credit risk. Values above 3σ typically indicate very safe companies.
                """)
                
                # Benchmark comparison
                st.markdown("---")
                st.subheader(t("benchmark_companies"))
                
                benchmark_tickers = ['AAPL', 'MSFT', 'BA', 'F', 'AAL']
                benchmark_data = []
                
                for bticker in benchmark_tickers:
                    if bticker.upper() != ticker_input.upper():
                        bdata = get_credit_risk_data(bticker)
                        if bdata.get('success', False):
                            bV = bdata['market_cap'] + bdata['total_debt']
                            bDD = calculate_distance_to_default(bV, bdata['total_debt'], bdata['equity_volatility'], risk_free_rate, time_horizon)
                            bPD = calculate_probability_of_default(bDD)
                            benchmark_data.append({
                                'Ticker': bticker,
                                'Company': bdata['company_name'][:20],
                                'DD (σ)': f"{bDD:.2f}",
                                'PD (%)': f"{bPD*100:.2f}%"
                            })
                
                if benchmark_data:
                    # Add the analyzed company
                    benchmark_data.insert(0, {
                        'Ticker': ticker_input.upper(),
                        'Company': company_name[:20] + " ⭐",
                        'DD (σ)': f"{DD:.2f}",
                        'PD (%)': f"{PD*100:.2f}%"
                    })
                    
                    bench_df = pd.DataFrame(benchmark_data)
                    st.dataframe(bench_df, use_container_width=True, hide_index=True)
                
            else:
                st.error(t("data_unavailable"))
                if 'error' in data:
                    st.caption(f"Error: {data['error']}")
    
    # ML Model section (informational)
    st.markdown("---")
    with st.expander(f"ℹ️ {t('ml_model')}"):
        st.markdown(f"""
        **{t('ml_explanation')}**
        
        The ML model was trained on the American Bankruptcy Dataset containing:
        - 78,682 firm-year observations (1999-2018)
        - 18 financial ratios (profitability, leverage, liquidity, activity)
        - Binary classification: bankrupt vs. non-bankrupt
        
        **Model Performance:**
        - Validation AUC-ROC: 0.739
        - Test AUC-ROC: 0.754
        
        **Top Predictive Features:**
        1. Industry sector (Division)
        2. X1 (likely a profitability ratio)
        3. X15 (likely a leverage ratio)
        
        **Limitation:** Live predictions would require mapping current financial statement data from Yahoo Finance to the exact ratios used in training (X1-X18 from Compustat). This mapping is non-trivial and would require access to the original feature definitions.
        """)
