# -*- coding: utf-8 -*-
"""
Financial Dashboard - Multi-asset Comparison
Enhanced version with metrics, drawdowns, news, and multilingual support
"""

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime, timedelta
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import feedparser
import requests
import json

# =============================================================================
# TRANSLATIONS
# =============================================================================
TRANSLATIONS = {
    "English": {
        # General
        "page_title": "Financial Dashboard",
        "main_title": "📈 Financial Dashboard",
        "comparison": "Comparison",
        "vs": "vs",
        "years": "years",
        "over": "over",
        
        # Sidebar
        "settings": "⚙️ Settings",
        "language": "🌐 Language",
        "asset_selection": "Asset Selection",
        "first_asset": "First asset",
        "second_asset": "Second asset",
        "period": "Period",
        "num_years": "Number of years",
        "display_options": "Display Options",
        "show_normalized": "Show normalized prices",
        "show_drawdown": "Show drawdowns",
        "show_volume": "Show volumes",
        "refresh_data": "🔄 Refresh data",
        "last_update": "Last update",
        "created_with": "Dashboard created with Streamlit",
        
        # Asset categories
        "cryptocurrencies": "Cryptocurrencies",
        "indices": "Indices",
        "tech_stocks": "Tech Stocks",
        "commodities": "Commodities",
        
        # Metrics
        "key_metrics": "📊 Key Metrics",
        "return": "Return",
        "volatility": "Volatility",
        "current_price": "Current Price",
        "sharpe": "Sharpe",
        
        # Charts
        "performance_comparison": "📈 Performance Comparison",
        "normalized_prices": "Normalized prices",
        "prices": "Prices",
        "normalized_price_zscore": "Normalized Price (z-score)",
        "price_usd": "Price ($)",
        "date": "Date",
        "asset": "Asset",
        
        # Drawdowns
        "drawdowns_title": "📉 Drawdowns (losses from peak)",
        "drawdowns_from_ath": "Drawdowns from all-time highs",
        "max_drawdown": "Max Drawdown",
        
        # Volume
        "trading_volumes": "📊 Trading Volumes",
        "volume": "Volume",
        
        # Correlation
        "correlation_analysis": "🔗 Correlation Analysis",
        "overall_correlation": "Overall Correlation",
        "rolling_correlation": "Rolling Correlation",
        "days": "days",
        "interpretation": "Interpretation",
        "strong_positive": "Strong positive correlation",
        "moderate": "Moderate correlation",
        "weak": "Weak correlation",
        "negative": "Negative correlation",
        
        # News
        "recent_news": "📰 Recent News",
        "no_news": "No news available",
        
        # Data
        "raw_data": "📋 Raw Data",
        "view_data": "View data",
        "merged_data": "View merged data",
        
        # Export
        "export_data": "💾 Export Data",
        "download": "📥 Download",
        
        # Errors
        "loading_data": "Loading data...",
        "error_loading": "Unable to load data. Please try again later.",
        "error_fetching": "Error fetching",
        
        # Economic Analysis
        "economic_analysis": "🌍 Economic Analysis by Continent",
        "select_continent": "Select a continent",
        "generate_analysis": "Generate Analysis",
        "analysis_disclaimer": "This analysis is generated by AI and should not be considered as financial advice.",
        "loading_analysis": "Generating economic analysis...",
        "api_key_required": "API Key Required",
        "api_key_help": "Get your free API key at",
        "enter_api_key": "Enter your Groq API key",
        "analysis_error": "Error generating analysis. Please check your API key and try again.",
        "continents": {
            "north_america": "North America",
            "south_america": "South America", 
            "europe": "Europe",
            "asia": "Asia",
            "africa": "Africa",
            "oceania": "Oceania"
        },
        "economic_indicators": "Key Economic Indicators",
        "ai_analysis": "AI Economic Analysis",
        "last_analysis": "Analysis generated on",
    },
    
    "Français": {
        # General
        "page_title": "Dashboard Financier",
        "main_title": "📈 Dashboard Financier",
        "comparison": "Comparaison",
        "vs": "vs",
        "years": "ans",
        "over": "sur",
        
        # Sidebar
        "settings": "⚙️ Paramètres",
        "language": "🌐 Langue",
        "asset_selection": "Sélection des actifs",
        "first_asset": "Premier actif",
        "second_asset": "Deuxième actif",
        "period": "Période",
        "num_years": "Nombre d'années",
        "display_options": "Options d'affichage",
        "show_normalized": "Afficher les prix normalisés",
        "show_drawdown": "Afficher les drawdowns",
        "show_volume": "Afficher les volumes",
        "refresh_data": "🔄 Rafraîchir les données",
        "last_update": "Dernière mise à jour",
        "created_with": "Dashboard créé avec Streamlit",
        
        # Asset categories
        "cryptocurrencies": "Cryptomonnaies",
        "indices": "Indices",
        "tech_stocks": "Actions Tech",
        "commodities": "Matières premières",
        
        # Metrics
        "key_metrics": "📊 Métriques clés",
        "return": "Rendement",
        "volatility": "Volatilité",
        "current_price": "Prix actuel",
        "sharpe": "Sharpe",
        
        # Charts
        "performance_comparison": "📈 Comparaison des performances",
        "normalized_prices": "Prix normalisés",
        "prices": "Prix",
        "normalized_price_zscore": "Prix normalisé (z-score)",
        "price_usd": "Prix ($)",
        "date": "Date",
        "asset": "Actif",
        
        # Drawdowns
        "drawdowns_title": "📉 Drawdowns (pertes depuis le plus haut)",
        "drawdowns_from_ath": "Drawdowns depuis les plus hauts historiques",
        "max_drawdown": "Drawdown max",
        
        # Volume
        "trading_volumes": "📊 Volumes d'échange",
        "volume": "Volume",
        
        # Correlation
        "correlation_analysis": "🔗 Analyse de corrélation",
        "overall_correlation": "Corrélation globale",
        "rolling_correlation": "Corrélation glissante",
        "days": "jours",
        "interpretation": "Interprétation",
        "strong_positive": "Forte corrélation positive",
        "moderate": "Corrélation modérée",
        "weak": "Faible corrélation",
        "negative": "Corrélation négative",
        
        # News
        "recent_news": "📰 Actualités récentes",
        "no_news": "Aucune actualité disponible",
        
        # Data
        "raw_data": "📋 Données brutes",
        "view_data": "Voir les données",
        "merged_data": "Voir les données fusionnées",
        
        # Export
        "export_data": "💾 Exporter les données",
        "download": "📥 Télécharger",
        
        # Errors
        "loading_data": "Chargement des données...",
        "error_loading": "Impossible de charger les données. Veuillez réessayer plus tard.",
        "error_fetching": "Erreur lors du chargement de",
        
        # Economic Analysis
        "economic_analysis": "🌍 Analyse Économique par Continent",
        "select_continent": "Sélectionner un continent",
        "generate_analysis": "Générer l'analyse",
        "analysis_disclaimer": "Cette analyse est générée par IA et ne constitue pas un conseil financier.",
        "loading_analysis": "Génération de l'analyse économique...",
        "api_key_required": "Clé API requise",
        "api_key_help": "Obtenez votre clé API gratuite sur",
        "enter_api_key": "Entrez votre clé API Groq",
        "analysis_error": "Erreur lors de la génération. Vérifiez votre clé API et réessayez.",
        "continents": {
            "north_america": "Amérique du Nord",
            "south_america": "Amérique du Sud",
            "europe": "Europe",
            "asia": "Asie",
            "africa": "Afrique",
            "oceania": "Océanie"
        },
        "economic_indicators": "Indicateurs Économiques Clés",
        "ai_analysis": "Analyse Économique IA",
        "last_analysis": "Analyse générée le",
    },
    
    "Español": {
        # General
        "page_title": "Panel Financiero",
        "main_title": "📈 Panel Financiero",
        "comparison": "Comparación",
        "vs": "vs",
        "years": "años",
        "over": "durante",
        
        # Sidebar
        "settings": "⚙️ Configuración",
        "language": "🌐 Idioma",
        "asset_selection": "Selección de activos",
        "first_asset": "Primer activo",
        "second_asset": "Segundo activo",
        "period": "Período",
        "num_years": "Número de años",
        "display_options": "Opciones de visualización",
        "show_normalized": "Mostrar precios normalizados",
        "show_drawdown": "Mostrar drawdowns",
        "show_volume": "Mostrar volúmenes",
        "refresh_data": "🔄 Actualizar datos",
        "last_update": "Última actualización",
        "created_with": "Panel creado con Streamlit",
        
        # Asset categories
        "cryptocurrencies": "Criptomonedas",
        "indices": "Índices",
        "tech_stocks": "Acciones tecnológicas",
        "commodities": "Materias primas",
        
        # Metrics
        "key_metrics": "📊 Métricas clave",
        "return": "Rendimiento",
        "volatility": "Volatilidad",
        "current_price": "Precio actual",
        "sharpe": "Sharpe",
        
        # Charts
        "performance_comparison": "📈 Comparación de rendimiento",
        "normalized_prices": "Precios normalizados",
        "prices": "Precios",
        "normalized_price_zscore": "Precio normalizado (z-score)",
        "price_usd": "Precio ($)",
        "date": "Fecha",
        "asset": "Activo",
        
        # Drawdowns
        "drawdowns_title": "📉 Drawdowns (pérdidas desde máximos)",
        "drawdowns_from_ath": "Drawdowns desde máximos históricos",
        "max_drawdown": "Drawdown máximo",
        
        # Volume
        "trading_volumes": "📊 Volúmenes de negociación",
        "volume": "Volumen",
        
        # Correlation
        "correlation_analysis": "🔗 Análisis de correlación",
        "overall_correlation": "Correlación global",
        "rolling_correlation": "Correlación móvil",
        "days": "días",
        "interpretation": "Interpretación",
        "strong_positive": "Fuerte correlación positiva",
        "moderate": "Correlación moderada",
        "weak": "Correlación débil",
        "negative": "Correlación negativa",
        
        # News
        "recent_news": "📰 Noticias recientes",
        "no_news": "No hay noticias disponibles",
        
        # Data
        "raw_data": "📋 Datos brutos",
        "view_data": "Ver datos",
        "merged_data": "Ver datos combinados",
        
        # Export
        "export_data": "💾 Exportar datos",
        "download": "📥 Descargar",
        
        # Errors
        "loading_data": "Cargando datos...",
        "error_loading": "No se pueden cargar los datos. Inténtelo de nuevo más tarde.",
        "error_fetching": "Error al cargar",
        
        # Economic Analysis
        "economic_analysis": "🌍 Análisis Económico por Continente",
        "select_continent": "Seleccionar un continente",
        "generate_analysis": "Generar Análisis",
        "analysis_disclaimer": "Este análisis es generado por IA y no debe considerarse como consejo financiero.",
        "loading_analysis": "Generando análisis económico...",
        "api_key_required": "Clave API requerida",
        "api_key_help": "Obtén tu clave API gratuita en",
        "enter_api_key": "Ingresa tu clave API de Groq",
        "analysis_error": "Error al generar el análisis. Verifica tu clave API e intenta de nuevo.",
        "continents": {
            "north_america": "América del Norte",
            "south_america": "América del Sur",
            "europe": "Europa",
            "asia": "Asia",
            "africa": "África",
            "oceania": "Oceanía"
        },
        "economic_indicators": "Indicadores Económicos Clave",
        "ai_analysis": "Análisis Económico IA",
        "last_analysis": "Análisis generado el",
    },
    
    "中文": {
        # General
        "page_title": "金融仪表板",
        "main_title": "📈 金融仪表板",
        "comparison": "比较",
        "vs": "与",
        "years": "年",
        "over": "期间",
        
        # Sidebar
        "settings": "⚙️ 设置",
        "language": "🌐 语言",
        "asset_selection": "资产选择",
        "first_asset": "第一资产",
        "second_asset": "第二资产",
        "period": "时间段",
        "num_years": "年数",
        "display_options": "显示选项",
        "show_normalized": "显示标准化价格",
        "show_drawdown": "显示回撤",
        "show_volume": "显示成交量",
        "refresh_data": "🔄 刷新数据",
        "last_update": "最后更新",
        "created_with": "使用Streamlit创建的仪表板",
        
        # Asset categories
        "cryptocurrencies": "加密货币",
        "indices": "指数",
        "tech_stocks": "科技股",
        "commodities": "大宗商品",
        
        # Metrics
        "key_metrics": "📊 关键指标",
        "return": "回报率",
        "volatility": "波动率",
        "current_price": "当前价格",
        "sharpe": "夏普比率",
        
        # Charts
        "performance_comparison": "📈 绩效比较",
        "normalized_prices": "标准化价格",
        "prices": "价格",
        "normalized_price_zscore": "标准化价格 (z-score)",
        "price_usd": "价格 ($)",
        "date": "日期",
        "asset": "资产",
        
        # Drawdowns
        "drawdowns_title": "📉 回撤（从峰值的损失）",
        "drawdowns_from_ath": "从历史高点的回撤",
        "max_drawdown": "最大回撤",
        
        # Volume
        "trading_volumes": "📊 交易量",
        "volume": "成交量",
        
        # Correlation
        "correlation_analysis": "🔗 相关性分析",
        "overall_correlation": "总体相关性",
        "rolling_correlation": "滚动相关性",
        "days": "天",
        "interpretation": "解释",
        "strong_positive": "强正相关",
        "moderate": "中等相关",
        "weak": "弱相关",
        "negative": "负相关",
        
        # News
        "recent_news": "📰 最新消息",
        "no_news": "暂无新闻",
        
        # Data
        "raw_data": "📋 原始数据",
        "view_data": "查看数据",
        "merged_data": "查看合并数据",
        
        # Export
        "export_data": "💾 导出数据",
        "download": "📥 下载",
        
        # Errors
        "loading_data": "加载数据中...",
        "error_loading": "无法加载数据，请稍后再试。",
        "error_fetching": "获取数据时出错",
        
        # Economic Analysis
        "economic_analysis": "🌍 各大洲经济分析",
        "select_continent": "选择一个大洲",
        "generate_analysis": "生成分析",
        "analysis_disclaimer": "此分析由AI生成，不应被视为财务建议。",
        "loading_analysis": "正在生成经济分析...",
        "api_key_required": "需要API密钥",
        "api_key_help": "在此获取免费API密钥",
        "enter_api_key": "输入您的Groq API密钥",
        "analysis_error": "生成分析时出错。请检查您的API密钥并重试。",
        "continents": {
            "north_america": "北美洲",
            "south_america": "南美洲",
            "europe": "欧洲",
            "asia": "亚洲",
            "africa": "非洲",
            "oceania": "大洋洲"
        },
        "economic_indicators": "关键经济指标",
        "ai_analysis": "AI经济分析",
        "last_analysis": "分析生成于",
    },
    
    "Русский": {
        # General
        "page_title": "Финансовая панель",
        "main_title": "📈 Финансовая панель",
        "comparison": "Сравнение",
        "vs": "и",
        "years": "лет",
        "over": "за",
        
        # Sidebar
        "settings": "⚙️ Настройки",
        "language": "🌐 Язык",
        "asset_selection": "Выбор активов",
        "first_asset": "Первый актив",
        "second_asset": "Второй актив",
        "period": "Период",
        "num_years": "Количество лет",
        "display_options": "Параметры отображения",
        "show_normalized": "Показать нормализованные цены",
        "show_drawdown": "Показать просадки",
        "show_volume": "Показать объёмы",
        "refresh_data": "🔄 Обновить данные",
        "last_update": "Последнее обновление",
        "created_with": "Панель создана с помощью Streamlit",
        
        # Asset categories
        "cryptocurrencies": "Криптовалюты",
        "indices": "Индексы",
        "tech_stocks": "Технологические акции",
        "commodities": "Сырьевые товары",
        
        # Metrics
        "key_metrics": "📊 Ключевые показатели",
        "return": "Доходность",
        "volatility": "Волатильность",
        "current_price": "Текущая цена",
        "sharpe": "Шарп",
        
        # Charts
        "performance_comparison": "📈 Сравнение эффективности",
        "normalized_prices": "Нормализованные цены",
        "prices": "Цены",
        "normalized_price_zscore": "Нормализованная цена (z-score)",
        "price_usd": "Цена ($)",
        "date": "Дата",
        "asset": "Актив",
        
        # Drawdowns
        "drawdowns_title": "📉 Просадки (потери от максимума)",
        "drawdowns_from_ath": "Просадки от исторических максимумов",
        "max_drawdown": "Макс. просадка",
        
        # Volume
        "trading_volumes": "📊 Объёмы торгов",
        "volume": "Объём",
        
        # Correlation
        "correlation_analysis": "🔗 Анализ корреляции",
        "overall_correlation": "Общая корреляция",
        "rolling_correlation": "Скользящая корреляция",
        "days": "дней",
        "interpretation": "Интерпретация",
        "strong_positive": "Сильная положительная корреляция",
        "moderate": "Умеренная корреляция",
        "weak": "Слабая корреляция",
        "negative": "Отрицательная корреляция",
        
        # News
        "recent_news": "📰 Последние новости",
        "no_news": "Новостей нет",
        
        # Data
        "raw_data": "📋 Исходные данные",
        "view_data": "Посмотреть данные",
        "merged_data": "Посмотреть объединённые данные",
        
        # Export
        "export_data": "💾 Экспорт данных",
        "download": "📥 Скачать",
        
        # Errors
        "loading_data": "Загрузка данных...",
        "error_loading": "Невозможно загрузить данные. Попробуйте позже.",
        "error_fetching": "Ошибка при загрузке",
        
        # Economic Analysis
        "economic_analysis": "🌍 Экономический Анализ по Континентам",
        "select_continent": "Выберите континент",
        "generate_analysis": "Создать анализ",
        "analysis_disclaimer": "Этот анализ создан ИИ и не является финансовой рекомендацией.",
        "loading_analysis": "Генерация экономического анализа...",
        "api_key_required": "Требуется API ключ",
        "api_key_help": "Получите бесплатный API ключ на",
        "enter_api_key": "Введите ваш Groq API ключ",
        "analysis_error": "Ошибка при генерации анализа. Проверьте API ключ и попробуйте снова.",
        "continents": {
            "north_america": "Северная Америка",
            "south_america": "Южная Америка",
            "europe": "Европа",
            "asia": "Азия",
            "africa": "Африка",
            "oceania": "Океания"
        },
        "economic_indicators": "Ключевые Экономические Показатели",
        "ai_analysis": "ИИ Экономический Анализ",
        "last_analysis": "Анализ создан",
    },
    
    "العربية": {
        # General
        "page_title": "لوحة المعلومات المالية",
        "main_title": "📈 لوحة المعلومات المالية",
        "comparison": "مقارنة",
        "vs": "مقابل",
        "years": "سنوات",
        "over": "خلال",
        
        # Sidebar
        "settings": "⚙️ الإعدادات",
        "language": "🌐 اللغة",
        "asset_selection": "اختيار الأصول",
        "first_asset": "الأصل الأول",
        "second_asset": "الأصل الثاني",
        "period": "الفترة",
        "num_years": "عدد السنوات",
        "display_options": "خيارات العرض",
        "show_normalized": "عرض الأسعار المعيارية",
        "show_drawdown": "عرض التراجعات",
        "show_volume": "عرض أحجام التداول",
        "refresh_data": "🔄 تحديث البيانات",
        "last_update": "آخر تحديث",
        "created_with": "لوحة معلومات تم إنشاؤها باستخدام Streamlit",
        
        # Asset categories
        "cryptocurrencies": "العملات المشفرة",
        "indices": "المؤشرات",
        "tech_stocks": "أسهم التكنولوجيا",
        "commodities": "السلع",
        
        # Metrics
        "key_metrics": "📊 المؤشرات الرئيسية",
        "return": "العائد",
        "volatility": "التقلب",
        "current_price": "السعر الحالي",
        "sharpe": "شارب",
        
        # Charts
        "performance_comparison": "📈 مقارنة الأداء",
        "normalized_prices": "الأسعار المعيارية",
        "prices": "الأسعار",
        "normalized_price_zscore": "السعر المعياري (z-score)",
        "price_usd": "السعر ($)",
        "date": "التاريخ",
        "asset": "الأصل",
        
        # Drawdowns
        "drawdowns_title": "📉 التراجعات (الخسائر من الذروة)",
        "drawdowns_from_ath": "التراجعات من أعلى المستويات التاريخية",
        "max_drawdown": "أقصى تراجع",
        
        # Volume
        "trading_volumes": "📊 أحجام التداول",
        "volume": "الحجم",
        
        # Correlation
        "correlation_analysis": "🔗 تحليل الارتباط",
        "overall_correlation": "الارتباط الكلي",
        "rolling_correlation": "الارتباط المتحرك",
        "days": "يوم",
        "interpretation": "التفسير",
        "strong_positive": "ارتباط إيجابي قوي",
        "moderate": "ارتباط معتدل",
        "weak": "ارتباط ضعيف",
        "negative": "ارتباط سلبي",
        
        # News
        "recent_news": "📰 آخر الأخبار",
        "no_news": "لا توجد أخبار متاحة",
        
        # Data
        "raw_data": "📋 البيانات الخام",
        "view_data": "عرض البيانات",
        "merged_data": "عرض البيانات المدمجة",
        
        # Export
        "export_data": "💾 تصدير البيانات",
        "download": "📥 تحميل",
        
        # Errors
        "loading_data": "جاري تحميل البيانات...",
        "error_loading": "تعذر تحميل البيانات. يرجى المحاولة مرة أخرى لاحقاً.",
        "error_fetching": "خطأ في جلب",
        
        # Economic Analysis
        "economic_analysis": "🌍 التحليل الاقتصادي حسب القارة",
        "select_continent": "اختر قارة",
        "generate_analysis": "إنشاء التحليل",
        "analysis_disclaimer": "هذا التحليل تم إنشاؤه بواسطة الذكاء الاصطناعي ولا ينبغي اعتباره نصيحة مالية.",
        "loading_analysis": "جاري إنشاء التحليل الاقتصادي...",
        "api_key_required": "مفتاح API مطلوب",
        "api_key_help": "احصل على مفتاح API المجاني من",
        "enter_api_key": "أدخل مفتاح Groq API الخاص بك",
        "analysis_error": "خطأ في إنشاء التحليل. يرجى التحقق من مفتاح API والمحاولة مرة أخرى.",
        "continents": {
            "north_america": "أمريكا الشمالية",
            "south_america": "أمريكا الجنوبية",
            "europe": "أوروبا",
            "asia": "آسيا",
            "africa": "أفريقيا",
            "oceania": "أوقيانوسيا"
        },
        "economic_indicators": "المؤشرات الاقتصادية الرئيسية",
        "ai_analysis": "التحليل الاقتصادي بالذكاء الاصطناعي",
        "last_analysis": "تم إنشاء التحليل في",
    },
}

# Language configuration (RTL support)
RTL_LANGUAGES = ["العربية"]

def get_text(key: str) -> str:
    """Get translated text for the current language."""
    lang = st.session_state.get("language", "English")
    return TRANSLATIONS.get(lang, TRANSLATIONS["English"]).get(key, key)

def t(key: str) -> str:
    """Shorthand for get_text."""
    return get_text(key)


# =============================================================================
# PAGE CONFIGURATION (must be first Streamlit command)
# =============================================================================
st.set_page_config(
    page_title="Financial Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =============================================================================
# SESSION STATE INITIALIZATION
# =============================================================================
if "language" not in st.session_state:
    st.session_state.language = "English"


# =============================================================================
# CUSTOM CSS - PROFESSIONAL PARCHMENT THEME
# =============================================================================
def apply_custom_css():
    """Apply custom CSS including RTL support and professional parchment theme."""
    is_rtl = st.session_state.language in RTL_LANGUAGES
    direction = "rtl" if is_rtl else "ltr"
    text_align = "right" if is_rtl else "left"
    
    st.markdown(f"""
    <style>
        /* ============================================
           GLOBAL STYLES
           ============================================ */
        
        /* Import Google Font for professional look */
        @import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&family=Source+Sans+Pro:wght@400;600;700&display=swap');
        
        /* Main app background */
        .stApp {{
            background: linear-gradient(135deg, #F5E6C8 0%, #EDE0C8 50%, #F0E4CE 100%);
            font-family: 'Source Sans Pro', sans-serif;
        }}
        
        /* Main container */
        .main .block-container {{
            direction: {direction};
            text-align: {text_align};
            padding-top: 2rem;
            max-width: 1200px;
        }}
        
        /* ============================================
           TYPOGRAPHY
           ============================================ */
        
        /* Main title */
        h1 {{
            font-family: 'Libre Baskerville', serif !important;
            color: #4A3728 !important;
            font-weight: 700 !important;
            letter-spacing: 0.5px;
            border-bottom: 3px solid #8B7355;
            padding-bottom: 0.5rem;
            margin-bottom: 1.5rem !important;
        }}
        
        /* Section headers */
        h2 {{
            font-family: 'Libre Baskerville', serif !important;
            color: #5D4E37 !important;
            font-weight: 700 !important;
            font-size: 1.5rem !important;
            margin-top: 1rem !important;
            padding-left: 0.5rem;
            border-left: 4px solid #8B7355;
        }}
        
        /* Subsection headers */
        h3 {{
            font-family: 'Source Sans Pro', sans-serif !important;
            color: #6B5B4A !important;
            font-weight: 600 !important;
            font-size: 1.1rem !important;
            text-transform: uppercase;
            letter-spacing: 1px;
        }}
        
        /* Paragraph text */
        p, span, label {{
            color: #4A3F35 !important;
        }}
        
        /* ============================================
           SIDEBAR
           ============================================ */
        
        [data-testid="stSidebar"] {{
            background: linear-gradient(180deg, #E8D9BE 0%, #DFD0B8 100%);
            border-right: 1px solid #C4B59B;
            box-shadow: 2px 0 10px rgba(74, 55, 40, 0.1);
        }}
        
        [data-testid="stSidebar"] h2 {{
            border-left: none !important;
            border-bottom: 2px solid #A89880;
            padding-bottom: 0.5rem;
            padding-left: 0 !important;
            font-size: 1.2rem !important;
        }}
        
        [data-testid="stSidebar"] h3 {{
            color: #5D4E37 !important;
            font-size: 0.9rem !important;
            margin-top: 1.5rem !important;
            margin-bottom: 0.5rem !important;
        }}
        
        /* Sidebar labels */
        [data-testid="stSidebar"] label {{
            color: #4A3F35 !important;
            font-weight: 600 !important;
            font-size: 0.85rem !important;
        }}
        
        /* Sidebar caption */
        [data-testid="stSidebar"] .stCaption {{
            color: #7A6B5A !important;
            font-size: 0.75rem !important;
        }}
        
        /* ============================================
           SELECTBOX / DROPDOWN
           ============================================ */
        
        [data-testid="stSelectbox"] > div > div {{
            background-color: #FFFEF9 !important;
            border: 2px solid #B8A88A !important;
            border-radius: 8px !important;
            color: #3D3428 !important;
            font-weight: 500 !important;
            transition: all 0.2s ease;
        }}
        
        [data-testid="stSelectbox"] > div > div:hover {{
            border-color: #8B7355 !important;
            box-shadow: 0 2px 8px rgba(74, 55, 40, 0.15);
        }}
        
        [data-testid="stSelectbox"] > div > div:focus-within {{
            border-color: #6B5344 !important;
            box-shadow: 0 0 0 3px rgba(107, 83, 68, 0.2);
        }}
        
        /* Selectbox label - IMPORTANT FIX */
        [data-testid="stSelectbox"] > label {{
            color: #4A3F35 !important;
            font-weight: 600 !important;
            font-size: 0.9rem !important;
            margin-bottom: 0.3rem !important;
        }}
        
        /* ============================================
           SLIDER
           ============================================ */
        
        [data-testid="stSlider"] > label {{
            color: #4A3F35 !important;
            font-weight: 600 !important;
        }}
        
        [data-testid="stSlider"] [data-baseweb="slider"] {{
            margin-top: 0.5rem;
        }}
        
        /* Slider track */
        [data-testid="stSlider"] [role="slider"] {{
            background-color: #8B7355 !important;
        }}
        
        /* ============================================
           CHECKBOX
           ============================================ */
        
        [data-testid="stCheckbox"] {{
            padding: 0.3rem 0;
        }}
        
        [data-testid="stCheckbox"] label {{
            color: #4A3F35 !important;
            font-weight: 500 !important;
        }}
        
        [data-testid="stCheckbox"] label span[data-baseweb="checkbox"] {{
            border-color: #8B7355 !important;
        }}
        
        /* ============================================
           METRIC CARDS
           ============================================ */
        
        [data-testid="stMetric"] {{
            background: linear-gradient(145deg, #FFFEFA 0%, #FBF6ED 100%);
            padding: 1.25rem 1.5rem;
            border-radius: 12px;
            border: 1px solid #D4C5A9;
            box-shadow: 0 4px 15px rgba(74, 55, 40, 0.08),
                        inset 0 1px 0 rgba(255, 255, 255, 0.8);
            transition: all 0.3s ease;
        }}
        
        [data-testid="stMetric"]:hover {{
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(74, 55, 40, 0.12),
                        inset 0 1px 0 rgba(255, 255, 255, 0.8);
            border-color: #B8A88A;
        }}
        
        /* Metric label */
        [data-testid="stMetric"] label {{
            color: #6B5B4A !important;
            font-weight: 600 !important;
            font-size: 0.85rem !important;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }}
        
        /* Metric value */
        [data-testid="stMetric"] [data-testid="stMetricValue"] {{
            color: #3D3428 !important;
            font-family: 'Libre Baskerville', serif !important;
            font-weight: 700 !important;
            font-size: 1.8rem !important;
        }}
        
        /* Metric delta positive */
        [data-testid="stMetric"] [data-testid="stMetricDelta"] {{
            font-weight: 600 !important;
        }}
        
        /* ============================================
           BUTTONS
           ============================================ */
        
        .stButton > button {{
            background: linear-gradient(145deg, #FFFEFA 0%, #F5EFE0 100%);
            color: #4A3F35 !important;
            border: 2px solid #B8A88A;
            border-radius: 10px;
            padding: 0.7rem 1.5rem;
            font-weight: 600;
            font-size: 0.9rem;
            letter-spacing: 0.3px;
            transition: all 0.3s ease;
            box-shadow: 0 2px 8px rgba(74, 55, 40, 0.1);
        }}
        
        .stButton > button:hover {{
            background: linear-gradient(145deg, #F5EFE0 0%, #EDE5D3 100%);
            border-color: #8B7355;
            transform: translateY(-1px);
            box-shadow: 0 4px 12px rgba(74, 55, 40, 0.15);
        }}
        
        .stButton > button:active {{
            transform: translateY(0);
            box-shadow: 0 1px 4px rgba(74, 55, 40, 0.1);
        }}
        
        /* Button text and icon */
        .stButton > button span {{
            color: #4A3F35 !important;
        }}
        
        .stButton > button p {{
            color: #4A3F35 !important;
            margin: 0;
        }}
        
        /* Download buttons - IMPROVED */
        .stDownloadButton > button {{
            background: linear-gradient(145deg, #5D4E37 0%, #4A3F35 100%);
            color: #FFFEFA !important;
            border: none;
            border-radius: 8px;
            padding: 0.75rem 1.5rem;
            font-weight: 600;
            font-size: 0.9rem;
            letter-spacing: 0.3px;
            transition: all 0.3s ease;
            box-shadow: 0 3px 10px rgba(74, 55, 40, 0.2);
            min-width: 200px;
            white-space: nowrap;
        }}
        
        .stDownloadButton > button:hover {{
            background: linear-gradient(145deg, #6B5B4A 0%, #5D4E37 100%);
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(74, 55, 40, 0.25);
        }}
        
        .stDownloadButton > button:active {{
            transform: translateY(0);
        }}
        
        /* Fix text visibility inside download button */
        .stDownloadButton > button span {{
            color: #FFFEFA !important;
        }}
        
        .stDownloadButton > button p {{
            color: #FFFEFA !important;
            margin: 0;
        }}
        
        /* ============================================
           EXPANDERS
           ============================================ */
        
        [data-testid="stExpander"] {{
            background-color: #FFFEFA;
            border: 1px solid #D4C5A9;
            border-radius: 10px;
            overflow: hidden;
            margin-bottom: 0.5rem;
            box-shadow: 0 2px 8px rgba(74, 55, 40, 0.06);
        }}
        
        [data-testid="stExpander"]:hover {{
            border-color: #B8A88A;
        }}
        
        /* Expander header */
        [data-testid="stExpander"] summary {{
            padding: 1rem 1.25rem;
            font-weight: 600;
            color: #4A3F35 !important;
            background-color: #FAF5E8;
        }}
        
        [data-testid="stExpander"] summary:hover {{
            background-color: #F5EFE0;
        }}
        
        /* Expander header text - IMPORTANT FIX */
        [data-testid="stExpander"] summary span {{
            color: #4A3F35 !important;
            font-weight: 600 !important;
        }}
        
        /* Expander content */
        [data-testid="stExpander"] [data-testid="stExpanderDetails"] {{
            padding: 1rem;
            background-color: #FFFEFA;
        }}
        
        /* ============================================
           DATAFRAMES / TABLES
           ============================================ */
        
        [data-testid="stDataFrame"] {{
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 2px 10px rgba(74, 55, 40, 0.08);
        }}
        
        [data-testid="stDataFrame"] > div {{
            background-color: #FFFEFA;
        }}
        
        /* ============================================
           DIVIDERS
           ============================================ */
        
        hr {{
            border: none;
            height: 1px;
            background: linear-gradient(90deg, transparent, #C4B59B, transparent);
            margin: 2rem 0;
        }}
        
        /* ============================================
           INFO / ALERTS
           ============================================ */
        
        .stAlert {{
            background-color: #FAF5E8;
            border: 1px solid #D4C5A9;
            border-radius: 8px;
            color: #4A3F35;
        }}
        
        /* ============================================
           PLOTLY CHARTS CONTAINER
           ============================================ */
        
        [data-testid="stPlotlyChart"] {{
            background-color: #FFFEFA;
            border-radius: 12px;
            padding: 1rem;
            box-shadow: 0 4px 15px rgba(74, 55, 40, 0.08);
            border: 1px solid #E8DCC8;
        }}
        
        /* ============================================
           MARKDOWN TEXT
           ============================================ */
        
        .stMarkdown {{
            color: #4A3F35;
        }}
        
        .stMarkdown strong {{
            color: #3D3428 !important;
            font-weight: 700;
        }}
        
        .stMarkdown a {{
            color: #6B5344 !important;
            text-decoration: underline;
        }}
        
        .stMarkdown a:hover {{
            color: #8B7355 !important;
        }}
        
        /* ============================================
           CAPTIONS
           ============================================ */
        
        .stCaption, small {{
            color: #7A6B5A !important;
            font-size: 0.8rem !important;
        }}
        
        /* ============================================
           SCROLLBAR (optional nice touch)
           ============================================ */
        
        ::-webkit-scrollbar {{
            width: 8px;
            height: 8px;
        }}
        
        ::-webkit-scrollbar-track {{
            background: #EDE0C8;
        }}
        
        ::-webkit-scrollbar-thumb {{
            background: #B8A88A;
            border-radius: 4px;
        }}
        
        ::-webkit-scrollbar-thumb:hover {{
            background: #8B7355;
        }}
        
        /* ============================================
           RESPONSIVE DESIGN - TABLET (768px - 1024px)
           ============================================ */
        
        @media screen and (max-width: 1024px) {{
            /* Main container */
            .main .block-container {{
                padding-left: 1rem;
                padding-right: 1rem;
                max-width: 100%;
            }}
            
            /* Title */
            h1 {{
                font-size: 1.8rem !important;
            }}
            
            h2 {{
                font-size: 1.3rem !important;
            }}
            
            /* Metric cards */
            [data-testid="stMetric"] {{
                padding: 1rem;
            }}
            
            [data-testid="stMetric"] [data-testid="stMetricValue"] {{
                font-size: 1.5rem !important;
            }}
            
            [data-testid="stMetric"] label {{
                font-size: 0.75rem !important;
            }}
            
            /* Buttons */
            .stDownloadButton > button {{
                min-width: 160px;
                padding: 0.6rem 1rem;
                font-size: 0.85rem;
            }}
            
            .stButton > button {{
                padding: 0.5rem 1rem;
                font-size: 0.85rem;
            }}
        }}
        
        /* ============================================
           RESPONSIVE DESIGN - MOBILE (< 768px)
           ============================================ */
        
        @media screen and (max-width: 768px) {{
            /* Hide sidebar by default on mobile */
            [data-testid="stSidebar"] {{
                min-width: 0 !important;
                width: 100% !important;
            }}
            
            /* Main container */
            .main .block-container {{
                padding-left: 0.5rem;
                padding-right: 0.5rem;
                padding-top: 1rem;
            }}
            
            /* Typography */
            h1 {{
                font-size: 1.5rem !important;
                padding-bottom: 0.3rem;
                margin-bottom: 1rem !important;
            }}
            
            h2 {{
                font-size: 1.15rem !important;
                padding-left: 0.4rem;
                border-left-width: 3px;
            }}
            
            h3 {{
                font-size: 0.95rem !important;
            }}
            
            /* Metric cards - stack nicely */
            [data-testid="stMetric"] {{
                padding: 0.8rem 1rem;
                border-radius: 10px;
                margin-bottom: 0.5rem;
            }}
            
            [data-testid="stMetric"] [data-testid="stMetricValue"] {{
                font-size: 1.3rem !important;
            }}
            
            [data-testid="stMetric"] label {{
                font-size: 0.7rem !important;
                letter-spacing: 0.3px;
            }}
            
            /* Buttons - full width on mobile */
            .stButton > button {{
                width: 100%;
                padding: 0.7rem 1rem;
                font-size: 0.9rem;
            }}
            
            .stDownloadButton > button {{
                width: 100%;
                min-width: unset;
                padding: 0.7rem 1rem;
                font-size: 0.85rem;
                margin-bottom: 0.5rem;
            }}
            
            /* Expanders */
            [data-testid="stExpander"] summary {{
                padding: 0.8rem 1rem;
                font-size: 0.9rem;
            }}
            
            /* Charts container */
            [data-testid="stPlotlyChart"] {{
                padding: 0.5rem;
                border-radius: 10px;
            }}
            
            /* Selectbox */
            [data-testid="stSelectbox"] > div > div {{
                font-size: 0.9rem;
            }}
            
            /* Dividers */
            hr {{
                margin: 1.5rem 0;
            }}
            
            /* News section - single column */
            [data-testid="stHorizontalBlock"] {{
                flex-direction: column;
            }}
            
            /* Correlation interpretation text */
            .stMarkdown {{
                font-size: 0.9rem;
            }}
        }}
        
        /* ============================================
           RESPONSIVE DESIGN - SMALL MOBILE (< 480px)
           ============================================ */
        
        @media screen and (max-width: 480px) {{
            /* Even smaller adjustments */
            h1 {{
                font-size: 1.3rem !important;
            }}
            
            h2 {{
                font-size: 1.05rem !important;
            }}
            
            [data-testid="stMetric"] {{
                padding: 0.6rem 0.8rem;
            }}
            
            [data-testid="stMetric"] [data-testid="stMetricValue"] {{
                font-size: 1.1rem !important;
            }}
            
            [data-testid="stMetric"] label {{
                font-size: 0.65rem !important;
            }}
            
            /* Sidebar adjustments */
            [data-testid="stSidebar"] h2 {{
                font-size: 1rem !important;
            }}
            
            [data-testid="stSidebar"] h3 {{
                font-size: 0.8rem !important;
            }}
        }}
        
        /* ============================================
           TOUCH-FRIENDLY IMPROVEMENTS
           ============================================ */
        
        @media (hover: none) and (pointer: coarse) {{
            /* Larger touch targets */
            .stButton > button,
            .stDownloadButton > button {{
                min-height: 48px;
            }}
            
            [data-testid="stCheckbox"] {{
                padding: 0.5rem 0;
            }}
            
            [data-testid="stCheckbox"] label {{
                font-size: 1rem !important;
            }}
            
            /* Remove hover effects on touch devices */
            [data-testid="stMetric"]:hover {{
                transform: none;
            }}
            
            .stButton > button:hover,
            .stDownloadButton > button:hover {{
                transform: none;
            }}
        }}
    </style>
    """, unsafe_allow_html=True)

apply_custom_css()


# =============================================================================
# CONSTANTS AND CONFIGURATION
# =============================================================================
ASSETS = {
    "cryptocurrencies": {
        "BTC-USD": "Bitcoin",
        "ETH-USD": "Ethereum",
        "SOL-USD": "Solana",
        "BNB-USD": "Binance Coin"
    },
    "indices": {
        "^GSPC": "S&P 500",
        "^IXIC": "NASDAQ",
        "^DJI": "Dow Jones",
        "^FCHI": "CAC 40",
        "^STOXX50E": "Euro Stoxx 50"
    },
    "tech_stocks": {
        "AAPL": "Apple",
        "MSFT": "Microsoft",
        "GOOGL": "Google",
        "NVDA": "NVIDIA",
        "META": "Meta"
    },
    "commodities": {
        "GC=F": "Gold",
        "SI=F": "Silver",
        "CL=F": "Oil (WTI)"
    }
}

# Create flat list for selectbox
ALL_ASSETS = {}
for category, assets in ASSETS.items():
    ALL_ASSETS.update(assets)

TICKER_TO_NAME = {ticker: name for ticker, name in ALL_ASSETS.items()}
NAME_TO_TICKER = {name: ticker for ticker, name in ALL_ASSETS.items()}


# =============================================================================
# DATA LOADING FUNCTIONS
# =============================================================================
@st.cache_data(ttl=3600)
def load_asset_data(ticker: str, years: int) -> pd.DataFrame:
    """Load historical data for an asset."""
    today = datetime.today()
    start_date = today - timedelta(days=365 * years)
    
    try:
        data = yf.Ticker(ticker).history(start=start_date, end=today)
        if data.empty:
            return pd.DataFrame()
        
        df = pd.DataFrame(data)
        df.reset_index(inplace=True)
        df['Date'] = pd.to_datetime(df['Date']).dt.date
        return df
    except Exception as e:
        st.error(f"{t('error_fetching')} {ticker}: {e}")
        return pd.DataFrame()


@st.cache_data(ttl=3600)
def get_asset_info(ticker: str) -> dict:
    """Get detailed asset information."""
    try:
        info = yf.Ticker(ticker).info
        return info
    except:
        return {}


def normalize_series(series: pd.Series) -> pd.Series:
    """Normalize a series (z-score)."""
    return (series - series.mean()) / series.std()


def calculate_returns(prices: pd.Series) -> float:
    """Calculate total return in percentage."""
    if len(prices) < 2:
        return 0.0
    return ((prices.iloc[-1] / prices.iloc[0]) - 1) * 100


def calculate_volatility(prices: pd.Series, annualize: bool = True) -> float:
    """Calculate volatility (standard deviation of returns)."""
    returns = prices.pct_change().dropna()
    vol = returns.std()
    if annualize:
        vol *= np.sqrt(252)
    return vol * 100


def calculate_drawdown(prices: pd.Series) -> pd.Series:
    """Calculate drawdown from all-time high."""
    peak = prices.cummax()
    drawdown = (prices - peak) / peak * 100
    return drawdown


def calculate_sharpe_ratio(prices: pd.Series, risk_free_rate: float = 0.04) -> float:
    """Calculate simplified Sharpe ratio."""
    returns = prices.pct_change().dropna()
    excess_return = returns.mean() * 252 - risk_free_rate
    volatility = returns.std() * np.sqrt(252)
    if volatility == 0:
        return 0
    return excess_return / volatility


@st.cache_data(ttl=3600)
def get_news(ticker: str) -> list:
    """Get news via Yahoo Finance RSS."""
    try:
        feed = feedparser.parse(f"https://feeds.finance.yahoo.com/rss/2.0/headline?s={ticker}")
        return feed.entries[:5]
    except:
        return []


# =============================================================================
# AI ECONOMIC ANALYSIS FUNCTIONS
# =============================================================================

# Continent economic indicators (major indices and ETFs)
CONTINENT_INDICATORS = {
    "north_america": {
        "indices": ["^GSPC", "^DJI", "^IXIC", "^GSPTSE"],
        "names": ["S&P 500", "Dow Jones", "NASDAQ", "TSX (Canada)"],
        "countries": ["USA", "Canada", "Mexico"]
    },
    "south_america": {
        "indices": ["^BVSP", "^MERV", "^IPSA"],
        "names": ["Bovespa (Brazil)", "MERVAL (Argentina)", "IPSA (Chile)"],
        "countries": ["Brazil", "Argentina", "Chile", "Colombia"]
    },
    "europe": {
        "indices": ["^STOXX50E", "^FTSE", "^GDAXI", "^FCHI"],
        "names": ["Euro Stoxx 50", "FTSE 100", "DAX", "CAC 40"],
        "countries": ["Germany", "UK", "France", "Italy", "Spain"]
    },
    "asia": {
        "indices": ["^N225", "^HSI", "000001.SS", "^BSESN"],
        "names": ["Nikkei 225", "Hang Seng", "Shanghai", "BSE Sensex"],
        "countries": ["Japan", "China", "India", "South Korea", "Singapore"]
    },
    "africa": {
        "indices": ["^JN0U.JO", "EGX30.CA"],
        "names": ["JSE Top 40 (South Africa)", "EGX 30 (Egypt)"],
        "countries": ["South Africa", "Egypt", "Nigeria", "Kenya"]
    },
    "oceania": {
        "indices": ["^AXJO", "^NZ50"],
        "names": ["ASX 200 (Australia)", "NZX 50 (New Zealand)"],
        "countries": ["Australia", "New Zealand"]
    }
}


def get_continent_data(continent_key: str) -> dict:
    """Fetch recent performance data for continent indices."""
    indicators = CONTINENT_INDICATORS.get(continent_key, {})
    results = {}
    
    for ticker, name in zip(indicators.get("indices", []), indicators.get("names", [])):
        try:
            data = yf.Ticker(ticker).history(period="1mo")
            if not data.empty:
                current = data['Close'].iloc[-1]
                month_ago = data['Close'].iloc[0]
                change_pct = ((current - month_ago) / month_ago) * 100
                results[name] = {
                    "current": current,
                    "change_1m": change_pct
                }
        except:
            continue
    
    return results


def generate_economic_analysis(continent_key: str, continent_name: str, api_key: str, language: str = "English") -> str:
    """Generate economic analysis using Groq API with Llama 3."""
    
    # Get market data for context
    market_data = get_continent_data(continent_key)
    indicators = CONTINENT_INDICATORS.get(continent_key, {})
    
    # Build market context
    market_context = ""
    for name, data in market_data.items():
        direction = "up" if data["change_1m"] > 0 else "down"
        market_context += f"- {name}: {data['current']:.2f} ({direction} {abs(data['change_1m']):.1f}% this month)\n"
    
    countries = ", ".join(indicators.get("countries", []))
    
    # Language instruction
    lang_instruction = {
        "English": "Respond in English.",
        "Français": "Réponds en français.",
        "Español": "Responde en español.",
        "中文": "请用中文回复。",
        "Русский": "Отвечай на русском языке.",
        "العربية": "الرجاء الرد باللغة العربية."
    }.get(language, "Respond in English.")
    
    prompt = f"""{lang_instruction}

You are an expert economic analyst. Provide a comprehensive but concise analysis of the current economic state of {continent_name}.

Current Market Data:
{market_context}

Major economies in this region: {countries}

Please provide:
1. **Overall Economic Health** (2-3 sentences)
2. **Key Trends** (3-4 bullet points on current economic trends)
3. **Challenges** (2-3 main challenges facing the region)
4. **Opportunities** (2-3 investment or growth opportunities)
5. **Short-term Outlook** (1-2 sentences on what to expect in the next 3-6 months)

Keep the analysis factual, balanced, and around 300-400 words total. Use the market data provided as context but also incorporate your knowledge of current economic conditions."""

    try:
        response = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            },
            json={
                "model": "llama-3.3-70b-versatile",
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a professional economic analyst providing insights on global markets and regional economies. Be factual, balanced, and insightful."
                    },
                    {
                        "role": "user", 
                        "content": prompt
                    }
                ],
                "temperature": 0.7,
                "max_tokens": 1000
            },
            timeout=30
        )
        
        if response.status_code == 200:
            return response.json()["choices"][0]["message"]["content"]
        else:
            return None
            
    except Exception as e:
        return None


# =============================================================================
# SIDEBAR - SETTINGS
# =============================================================================
with st.sidebar:
    # Language selector (always at top)
    st.subheader(t("language"))
    language = st.selectbox(
        "Language",
        options=list(TRANSLATIONS.keys()),
        index=list(TRANSLATIONS.keys()).index(st.session_state.language),
        label_visibility="collapsed"
    )
    
    if language != st.session_state.language:
        st.session_state.language = language
        st.rerun()
    
    st.markdown("---")
    st.header(t("settings"))
    
    st.subheader(t("asset_selection"))
    
    # First asset
    asset1_name = st.selectbox(
        t("first_asset"),
        options=list(NAME_TO_TICKER.keys()),
        index=list(NAME_TO_TICKER.keys()).index("Bitcoin")
    )
    asset1_ticker = NAME_TO_TICKER[asset1_name]
    
    # Second asset
    asset2_name = st.selectbox(
        t("second_asset"),
        options=list(NAME_TO_TICKER.keys()),
        index=list(NAME_TO_TICKER.keys()).index("S&P 500")
    )
    asset2_ticker = NAME_TO_TICKER[asset2_name]
    
    st.subheader(t("period"))
    years = st.slider(t("num_years"), min_value=1, max_value=10, value=5)
    
    st.subheader(t("display_options"))
    show_normalized = st.checkbox(t("show_normalized"), value=True)
    show_drawdown = st.checkbox(t("show_drawdown"), value=True)
    show_volume = st.checkbox(t("show_volume"), value=False)
    
    st.markdown("---")
    
    if st.button(t("refresh_data"), use_container_width=True):
        st.cache_data.clear()
        st.rerun()
    
    st.markdown("---")
    st.caption(t("created_with"))
    st.caption(f"{t('last_update')}: {datetime.now().strftime('%H:%M:%S')}")


# =============================================================================
# DATA LOADING
# =============================================================================
# =============================================================================
# MAIN CONTENT WITH TABS
# =============================================================================
st.title(t("main_title"))

# Create tabs for different sections
tab_comparison, tab_economic = st.tabs([
    f"📊 {t('performance_comparison')}", 
    f"🌍 {t('economic_analysis')}"
])

# =============================================================================
# TAB 1: ASSET COMPARISON
# =============================================================================
with tab_comparison:
    st.markdown(f"**{t('comparison')}:** {asset1_name} {t('vs')} {asset2_name} {t('over')} {years} {t('years')}")
    
    # Load with spinner
    with st.spinner(t("loading_data")):
        df1 = load_asset_data(asset1_ticker, years)
        df2 = load_asset_data(asset2_ticker, years)
    
    # Check data
    if df1.empty or df2.empty:
        st.error(t("error_loading"))
        st.stop()
    
    # KEY METRICS
    st.header(t("key_metrics"))
    
    col1, col2, col3, col4 = st.columns(4)
    
    return1 = calculate_returns(df1['Close'])
    with col1:
        st.metric(
            label=f"{t('return')} {asset1_name}",
            value=f"{return1:.1f}%",
            delta=f"{return1:.1f}%" if return1 != 0 else None
        )
    
    return2 = calculate_returns(df2['Close'])
    with col2:
        st.metric(
            label=f"{t('return')} {asset2_name}",
            value=f"{return2:.1f}%",
            delta=f"{return2:.1f}%" if return2 != 0 else None
        )
    
    vol1 = calculate_volatility(df1['Close'])
    with col3:
        st.metric(
            label=f"{t('volatility')} {asset1_name}",
            value=f"{vol1:.1f}%"
        )
    
    vol2 = calculate_volatility(df2['Close'])
    with col4:
        st.metric(
            label=f"{t('volatility')} {asset2_name}",
            value=f"{vol2:.1f}%"
        )
    
    col5, col6, col7, col8 = st.columns(4)
    
    with col5:
        current_price1 = df1['Close'].iloc[-1]
        st.metric(
            label=f"{t('current_price')} {asset1_name}",
            value=f"${current_price1:,.2f}"
        )
    
    with col6:
        current_price2 = df2['Close'].iloc[-1]
        st.metric(
            label=f"{t('current_price')} {asset2_name}",
            value=f"${current_price2:,.2f}"
        )
    
    with col7:
        sharpe1 = calculate_sharpe_ratio(df1['Close'])
        st.metric(
            label=f"{t('sharpe')} {asset1_name}",
            value=f"{sharpe1:.2f}"
        )
    
    with col8:
        sharpe2 = calculate_sharpe_ratio(df2['Close'])
        st.metric(
            label=f"{t('sharpe')} {asset2_name}",
            value=f"{sharpe2:.2f}"
        )
    
    # MAIN CHART - COMPARISON
    st.markdown("---")
    st.header(t("performance_comparison"))
    
    df1_plot = df1[['Date', 'Close']].copy()
    df2_plot = df2[['Date', 'Close']].copy()
    
    if show_normalized:
        df1_plot['Close'] = normalize_series(df1['Close'])
        df2_plot['Close'] = normalize_series(df2['Close'])
        y_label = t("normalized_price_zscore")
    else:
        y_label = t("price_usd")
    
    df1_plot = df1_plot.rename(columns={'Close': asset1_name})
    df2_plot = df2_plot.rename(columns={'Close': asset2_name})
    
    merged = pd.merge(df1_plot, df2_plot, on='Date', how='inner')
    merged_melted = merged.melt(id_vars=['Date'], var_name=t('asset'), value_name=t('prices'))
    
    chart_title = f"{t('normalized_prices') if show_normalized else t('prices')}: {asset1_name} {t('vs')} {asset2_name}"
    fig_main = px.line(
        merged_melted,
        x='Date',
        y=t('prices'),
        color=t('asset'),
        title=chart_title,
        color_discrete_map={asset1_name: '#C45B28', asset2_name: '#1B6B4A'},
        template='plotly_white'
    )
    
    fig_main.update_layout(
        xaxis_title=t("date"),
        yaxis_title=y_label,
        legend_title=dict(text=t("asset"), font=dict(color='#4A3F35', size=13, family="Source Sans Pro, sans-serif")),
        hovermode="x unified",
        height=450,
        margin=dict(l=20, r=20, t=60, b=40),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='#FFFEFA',
        font=dict(family="Source Sans Pro, sans-serif", color='#4A3F35', size=12),
        title_font=dict(family="Libre Baskerville, serif", color='#4A3728', size=16),
        legend=dict(
            bgcolor='#FFFEFA',
            bordercolor='#C4B59B',
            borderwidth=1,
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="center",
            x=0.5,
            font=dict(color='#3D3428', size=12),
            title_font=dict(color='#4A3F35', size=12)
        ),
        xaxis=dict(gridcolor='#E0D5C0', linecolor='#B8A88A', tickfont=dict(color='#4A3F35')),
        yaxis=dict(gridcolor='#E0D5C0', linecolor='#B8A88A', tickfont=dict(color='#4A3F35'))
    )
    
    fig_main.update_traces(line=dict(width=2.5))
    st.plotly_chart(fig_main, use_container_width=True)
    
    # DRAWDOWN CHART
    if show_drawdown:
        st.markdown("---")
        st.header(t("drawdowns_title"))
        
        df1['Drawdown'] = calculate_drawdown(df1['Close'])
        df2['Drawdown'] = calculate_drawdown(df2['Close'])
        
        fig_dd = go.Figure()
        
        fig_dd.add_trace(go.Scatter(
            x=df1['Date'],
            y=df1['Drawdown'],
            fill='tozeroy',
            name=asset1_name,
            line=dict(color='#C45B28', width=2),
            fillcolor='rgba(196, 91, 40, 0.25)'
        ))
        
        fig_dd.add_trace(go.Scatter(
            x=df2['Date'],
            y=df2['Drawdown'],
            fill='tozeroy',
            name=asset2_name,
            line=dict(color='#1B6B4A', width=2),
            fillcolor='rgba(27, 107, 74, 0.25)'
        ))
        
        fig_dd.update_layout(
            title=dict(text=t("drawdowns_from_ath"), font=dict(family="Libre Baskerville, serif", color='#4A3728', size=14)),
            xaxis_title=t("date"),
            yaxis_title="Drawdown (%)",
            template='plotly_white',
            hovermode="x unified",
            height=350,
            margin=dict(l=20, r=20, t=50, b=40),
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='#FFFEFA',
            font=dict(family="Source Sans Pro, sans-serif", color='#4A3F35', size=12),
            legend=dict(
                bgcolor='#FFFEFA',
                bordercolor='#C4B59B',
                borderwidth=1,
                orientation="h",
                yanchor="bottom",
                y=1.02,
                xanchor="center",
                x=0.5,
                font=dict(color='#3D3428', size=12)
            ),
            xaxis=dict(gridcolor='#E0D5C0', linecolor='#B8A88A', tickfont=dict(color='#4A3F35')),
            yaxis=dict(gridcolor='#E0D5C0', linecolor='#B8A88A', tickfont=dict(color='#4A3F35'))
        )
        
        st.plotly_chart(fig_dd, use_container_width=True)
        
        col_dd1, col_dd2 = st.columns(2)
        with col_dd1:
            max_dd1 = df1['Drawdown'].min()
            st.metric(f"{t('max_drawdown')} {asset1_name}", f"{max_dd1:.1f}%")
        with col_dd2:
            max_dd2 = df2['Drawdown'].min()
            st.metric(f"{t('max_drawdown')} {asset2_name}", f"{max_dd2:.1f}%")
    
    # VOLUME CHART
    if show_volume:
        st.markdown("---")
        st.header(t("trading_volumes"))
        
        fig_vol = make_subplots(rows=2, cols=1, shared_xaxes=True,
                                subplot_titles=(f"{t('volume')} {asset1_name}", f"{t('volume')} {asset2_name}"),
                                vertical_spacing=0.15)
        
        fig_vol.add_trace(
            go.Bar(x=df1['Date'], y=df1['Volume'], name=asset1_name, 
                   marker=dict(color='#C45B28', line=dict(width=0))),
            row=1, col=1
        )
        
        fig_vol.add_trace(
            go.Bar(x=df2['Date'], y=df2['Volume'], name=asset2_name, 
                   marker=dict(color='#1B6B4A', line=dict(width=0))),
            row=2, col=1
        )
        
        fig_vol.update_layout(
            height=450,
            template='plotly_white',
            showlegend=False,
            margin=dict(l=60, r=20, t=40, b=40),
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='#FFFEFA',
            font=dict(family="Source Sans Pro, sans-serif", color='#4A3F35', size=12),
            bargap=0.1
        )
        
        fig_vol.update_annotations(font=dict(color='#4A3728', size=13, family="Source Sans Pro, sans-serif"))
        fig_vol.update_xaxes(gridcolor='#E0D5C0', linecolor='#B8A88A', tickfont=dict(color='#4A3F35', size=11))
        fig_vol.update_yaxes(gridcolor='#E0D5C0', linecolor='#B8A88A', tickfont=dict(color='#4A3F35', size=11))
        
        st.plotly_chart(fig_vol, use_container_width=True)
    
    # CORRELATION
    st.markdown("---")
    st.header(t("correlation_analysis"))
    
    window = 30
    
    merged_corr = pd.merge(
        df1[['Date', 'Close']].rename(columns={'Close': 'Asset1'}),
        df2[['Date', 'Close']].rename(columns={'Close': 'Asset2'}),
        on='Date',
        how='inner'
    )
    
    merged_corr['Return1'] = merged_corr['Asset1'].pct_change()
    merged_corr['Return2'] = merged_corr['Asset2'].pct_change()
    merged_corr['Rolling_Corr'] = merged_corr['Return1'].rolling(window=window).corr(merged_corr['Return2'])
    
    col_corr1, col_corr2 = st.columns([1, 2])
    
    with col_corr1:
        overall_corr = merged_corr['Return1'].corr(merged_corr['Return2'])
        st.metric(t("overall_correlation"), f"{overall_corr:.3f}")
        
        st.markdown(f"""
        **{t('interpretation')}:**
        - **> 0.7**: {t('strong_positive')}
        - **0.3 - 0.7**: {t('moderate')}
        - **-0.3 - 0.3**: {t('weak')}
        - **< -0.3**: {t('negative')}
        """)
    
    with col_corr2:
        fig_corr = px.line(
            merged_corr,
            x='Date',
            y='Rolling_Corr',
            title=f"{t('rolling_correlation')} ({window} {t('days')})",
            template='plotly_white'
        )
        fig_corr.add_hline(y=0, line_dash="dash", line_color="#8B7355", line_width=1.5)
        fig_corr.update_traces(line=dict(color='#C45B28', width=2.5))
        fig_corr.update_layout(
            yaxis_title=t("overall_correlation"),
            height=300,
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='#FFFEFA',
            font=dict(family="Source Sans Pro, sans-serif", color='#4A3F35', size=12),
            title_font=dict(family="Libre Baskerville, serif", color='#4A3728', size=14),
            xaxis=dict(gridcolor='#E0D5C0', linecolor='#B8A88A', tickfont=dict(color='#4A3F35')),
            yaxis=dict(gridcolor='#E0D5C0', linecolor='#B8A88A', tickfont=dict(color='#4A3F35'))
        )
        st.plotly_chart(fig_corr, use_container_width=True)
    
    # NEWS
    st.markdown("---")
    st.header(t("recent_news"))
    
    col_news1, col_news2 = st.columns(2)
    
    with col_news1:
        st.subheader(f"📰 {asset1_name}")
        news1 = get_news(asset1_ticker)
        if news1:
            for entry in news1:
                st.markdown(f"**[{entry.title}]({entry.link})**")
                if hasattr(entry, 'published'):
                    st.caption(entry.published)
                st.markdown("---")
        else:
            st.info(t("no_news"))
    
    with col_news2:
        st.subheader(f"📰 {asset2_name}")
        news2 = get_news(asset2_ticker)
        if news2:
            for entry in news2:
                st.markdown(f"**[{entry.title}]({entry.link})**")
                if hasattr(entry, 'published'):
                    st.caption(entry.published)
                st.markdown("---")
        else:
            st.info(t("no_news"))
    
    # RAW DATA
    st.markdown("---")
    st.header(t("raw_data"))
    
    with st.expander(f"{t('view_data')} {asset1_name}"):
        st.dataframe(df1, use_container_width=True)
    
    with st.expander(f"{t('view_data')} {asset2_name}"):
        st.dataframe(df2, use_container_width=True)
    
    with st.expander(t("merged_data")):
        st.dataframe(merged, use_container_width=True)
    
    # EXPORT
    st.markdown("---")
    st.header(t("export_data"))
    
    col_export1, col_export2 = st.columns(2)
    
    with col_export1:
        csv1 = df1.to_csv(index=False)
        st.download_button(
            label=f"{t('download')} {asset1_name} (CSV)",
            data=csv1,
            file_name=f"{asset1_ticker}_{years}y.csv",
            mime="text/csv"
        )
    
    with col_export2:
        csv2 = df2.to_csv(index=False)
        st.download_button(
            label=f"{t('download')} {asset2_name} (CSV)",
            data=csv2,
            file_name=f"{asset2_ticker}_{years}y.csv",
            mime="text/csv"
        )

# =============================================================================
# TAB 2: ECONOMIC ANALYSIS BY CONTINENT
# =============================================================================
with tab_economic:
    st.markdown(f"*{t('analysis_disclaimer')}*")
    
    # API Key input
    st.subheader(t("api_key_required"))
    st.markdown(f"{t('api_key_help')} [console.groq.com](https://console.groq.com)")
    
    api_key = st.text_input(
        t("enter_api_key"),
        type="password",
        help="Get your free API key at console.groq.com"
    )
    
    st.markdown("---")
    
    # Continent selection
    continents_dict = t("continents")
    if isinstance(continents_dict, dict):
        continent_options = list(continents_dict.values())
        continent_keys = list(continents_dict.keys())
    else:
        continent_options = ["North America", "South America", "Europe", "Asia", "Africa", "Oceania"]
        continent_keys = ["north_america", "south_america", "europe", "asia", "africa", "oceania"]
    
    selected_continent = st.selectbox(
        t("select_continent"),
        options=continent_options
    )
    
    # Get the key for the selected continent
    selected_idx = continent_options.index(selected_continent)
    selected_key = continent_keys[selected_idx]
    
    # Display current market indicators for selected continent
    st.subheader(t("economic_indicators"))
    
    indicators = CONTINENT_INDICATORS.get(selected_key, {})
    market_data = get_continent_data(selected_key)
    
    if market_data:
        cols = st.columns(min(len(market_data), 4))
        for idx, (name, data) in enumerate(market_data.items()):
            with cols[idx % 4]:
                delta_color = "normal" if data["change_1m"] >= 0 else "inverse"
                st.metric(
                    label=name,
                    value=f"{data['current']:,.2f}",
                    delta=f"{data['change_1m']:+.1f}% (1M)"
                )
    else:
        st.info("Loading market data...")
    
    st.markdown("---")
    
    # Generate analysis button
    if st.button(t("generate_analysis"), use_container_width=True, disabled=not api_key):
        if api_key:
            with st.spinner(t("loading_analysis")):
                analysis = generate_economic_analysis(
                    selected_key, 
                    selected_continent, 
                    api_key,
                    st.session_state.language
                )
                
                if analysis:
                    st.subheader(t("ai_analysis"))
                    st.markdown(analysis)
                    st.caption(f"{t('last_analysis')}: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
                else:
                    st.error(t("analysis_error"))
        else:
            st.warning(t("api_key_required"))
    
    # Show placeholder if no API key
    if not api_key:
        st.info("👆 " + t("api_key_required") + " " + t("api_key_help") + " [console.groq.com](https://console.groq.com)")
